# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfEmailGetV1EmailMessagesResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :success,
    :data,
    :pagination
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :data => [Notifique.OpenApi.Model.NtfEmailEmailListItem.t],
    :pagination => Notifique.OpenApi.Model.NtfEmailGetV1EmailMessagesResponsePagination.t
  }

  alias Notifique.OpenApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, Notifique.OpenApi.Model.NtfEmailEmailListItem)
     |> Deserializer.deserialize(:pagination, :struct, Notifique.OpenApi.Model.NtfEmailGetV1EmailMessagesResponsePagination)
  end
end

