# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfAutoStepTrigger do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :stepKey,
    :stepType,
    :config
  ]

  @type t :: %__MODULE__{
    :stepKey => String.t,
    :stepType => String.t,
    :config => Notifique.OpenApi.Model.NtfAutoStepTriggerConfig.t
  }

  alias Notifique.OpenApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:config, :struct, Notifique.OpenApi.Model.NtfAutoStepTriggerConfig)
  end
end

