# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfWaWhatsAppInboundDetail do
  @moduledoc """
  Detalhe do inbound: texto e metadados mínimos; sem payload bruto do conector.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :instanceId,
    :from,
    :body,
    :receivedAt,
    :contentPreview,
    :mediaFetch,
    :instance,
    :type,
    :text
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :instanceId => String.t | nil,
    :from => String.t | nil,
    :body => String.t | nil,
    :receivedAt => DateTime.t | nil,
    :contentPreview => map() | nil,
    :mediaFetch => Notifique.OpenApi.Model.NtfWaWhatsAppInboundDetailMediaFetch.t | nil,
    :instance => Notifique.OpenApi.Model.NtfWaWhatsAppInboundListItemInstance.t | nil,
    :type => String.t | nil,
    :text => String.t | nil
  }

  alias Notifique.OpenApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:mediaFetch, :struct, Notifique.OpenApi.Model.NtfWaWhatsAppInboundDetailMediaFetch)
     |> Deserializer.deserialize(:instance, :struct, Notifique.OpenApi.Model.NtfWaWhatsAppInboundListItemInstance)
  end
end

