# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfContactGetV1TagsResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :success,
    :data
  ]

  @type t :: %__MODULE__{
    :success => boolean() | nil,
    :data => [Notifique.OpenApi.Model.NtfContactTag.t] | nil
  }

  alias Notifique.OpenApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, Notifique.OpenApi.Model.NtfContactTag)
  end
end

