# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfWaCreateWhatsAppCallRequestPayload do
  @moduledoc """
  speak: `text`, opcional `voice`/`language`. play: `audioUrl`. gather: objeto `gather`. template: `templateId`, `variables`.
  """

  @derive Jason.Encoder
  defstruct [
    :voice,
    :mediaUrl,
    :templateId,
    :variables,
    :text
  ]

  @type t :: %__MODULE__{
    :voice => String.t | nil,
    :mediaUrl => String.t | nil,
    :templateId => String.t | nil,
    :variables => Notifique.OpenApi.Model.NtfWaCreateWhatsAppCallRequestPayloadVariables.t | nil,
    :text => String.t | nil
  }

  alias Notifique.OpenApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:variables, :struct, Notifique.OpenApi.Model.NtfWaCreateWhatsAppCallRequestPayloadVariables)
  end
end

