# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfSmsSendSmsRequestOptions do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :priority,
    :speed,
    :webhook
  ]

  @type t :: %__MODULE__{
    :priority => String.t | nil,
    :speed => String.t | nil,
    :webhook => Notifique.OpenApi.Model.NtfSmsSendSmsRequestOptionsWebhook.t | nil
  }

  alias Notifique.OpenApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:webhook, :struct, Notifique.OpenApi.Model.NtfSmsSendSmsRequestOptionsWebhook)
  end
end

