# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfAddonsMarketingListRowPatch do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :status,
    :doubleOptInEnabled,
    :endedMessage
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :name => String.t | nil,
    :status => Notifique.OpenApi.Model.NtfAddonsMarketingListStatus.t | nil,
    :doubleOptInEnabled => boolean() | nil,
    :endedMessage => String.t | nil
  }

  alias Notifique.OpenApi.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, Notifique.OpenApi.Model.NtfAddonsMarketingListStatus)
  end
end

