# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfAddonsFormConfirmEnvelopeData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :subscriptionId,
    :formId,
    :status,
    :queuePosition,
    :confirmedAt,
    :alreadyConfirmed
  ]

  @type t :: %__MODULE__{
    :subscriptionId => String.t,
    :formId => String.t,
    :status => String.t,
    :queuePosition => integer() | nil,
    :confirmedAt => DateTime.t,
    :alreadyConfirmed => boolean() | nil
  }

  def decode(value) do
    value
  end
end

