# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfAutoGraphStep do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :stepKey,
    :stepType,
    :config
  ]

  @type t :: %__MODULE__{
    :stepKey => any(),
    :stepType => any(),
    :config => any()
  }

  def decode(value) do
    value
  end
end

