# NOTE: This file is auto generated by OpenAPI Generator 7.25.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Notifique.OpenApi.Model.NtfSmsGetV1SmsInboundResponsePagination do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :total,
    :page,
    :limit,
    :totalPages
  ]

  @type t :: %__MODULE__{
    :total => integer(),
    :page => integer(),
    :limit => integer(),
    :totalPages => integer()
  }

  def decode(value) do
    value
  end
end

