/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.notifique.sdk.openapi.models.NtfContactSegmentRuleValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.notifique.sdk.ApiClient;
/**
 * Uma regra do segmento. Campos dependem de type.
 */
@JsonPropertyOrder({
  NtfContactSegmentRule.JSON_PROPERTY_TYPE,
  NtfContactSegmentRule.JSON_PROPERTY_TAG_ID,
  NtfContactSegmentRule.JSON_PROPERTY_KEY,
  NtfContactSegmentRule.JSON_PROPERTY_VALUE,
  NtfContactSegmentRule.JSON_PROPERTY_OP,
  NtfContactSegmentRule.JSON_PROPERTY_VALUE_MATCH,
  NtfContactSegmentRule.JSON_PROPERTY_IGNORE_CASE,
  NtfContactSegmentRule.JSON_PROPERTY_FIELD,
  NtfContactSegmentRule.JSON_PROPERTY_TOPIC_ID,
  NtfContactSegmentRule.JSON_PROPERTY_SUBSCRIBED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfContactSegmentRule {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TAG(String.valueOf("tag")),
    
    PROPERTY(String.valueOf("property")),
    
    CONTACT_FIELD(String.valueOf("contactField")),
    
    TOPIC(String.valueOf("topic")),
    
    RECEIVE_MARKETING(String.valueOf("receiveMarketing"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_TAG_ID = "tagId";
  @javax.annotation.Nullable
  private String tagId;

  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nullable
  private String key;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private NtfContactSegmentRuleValue value;

  public static final String JSON_PROPERTY_OP = "op";
  @javax.annotation.Nullable
  private String op;

  /**
   * Legado para property STRING. Preferir op.
   */
  public enum ValueMatchEnum {
    EXACT(String.valueOf("exact")),
    
    CONTAINS(String.valueOf("contains"));

    private String value;

    ValueMatchEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ValueMatchEnum fromValue(String value) {
      for (ValueMatchEnum b : ValueMatchEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VALUE_MATCH = "valueMatch";
  @javax.annotation.Nullable
  private ValueMatchEnum valueMatch;

  public static final String JSON_PROPERTY_IGNORE_CASE = "ignoreCase";
  @javax.annotation.Nullable
  private Boolean ignoreCase;

  /**
   * Campo de plataforma quando type&#x3D;contactField
   */
  public enum FieldEnum {
    NAME(String.valueOf("name")),
    
    PHONE(String.valueOf("phone")),
    
    EMAIL(String.valueOf("email")),
    
    URL(String.valueOf("url")),
    
    TELEGRAM_PEER(String.valueOf("telegramPeer")),
    
    LANGUAGES(String.valueOf("languages")),
    
    HAS_PHONE(String.valueOf("hasPhone")),
    
    HAS_EMAIL(String.valueOf("hasEmail")),
    
    HAS_URL(String.valueOf("hasUrl")),
    
    HAS_TELEGRAM(String.valueOf("hasTelegram"));

    private String value;

    FieldEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FieldEnum fromValue(String value) {
      for (FieldEnum b : FieldEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FIELD = "field";
  @javax.annotation.Nullable
  private FieldEnum field;

  public static final String JSON_PROPERTY_TOPIC_ID = "topicId";
  @javax.annotation.Nullable
  private String topicId;

  public static final String JSON_PROPERTY_SUBSCRIBED = "subscribed";
  @javax.annotation.Nullable
  private Boolean subscribed;

  public NtfContactSegmentRule() { 
  }

  public NtfContactSegmentRule type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public NtfContactSegmentRule tagId(@javax.annotation.Nullable String tagId) {
    this.tagId = tagId;
    return this;
  }

  /**
   * Obrigatorio quando type&#x3D;tag
   * @return tagId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTagId() {
    return tagId;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagId(@javax.annotation.Nullable String tagId) {
    this.tagId = tagId;
  }


  public NtfContactSegmentRule key(@javax.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * Chave do campo personalizado (type&#x3D;property)
   * @return key
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKey(@javax.annotation.Nullable String key) {
    this.key = key;
  }


  public NtfContactSegmentRule value(@javax.annotation.Nullable NtfContactSegmentRuleValue value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public NtfContactSegmentRuleValue getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable NtfContactSegmentRuleValue value) {
    this.value = value;
  }


  public NtfContactSegmentRule op(@javax.annotation.Nullable String op) {
    this.op = op;
    return this;
  }

  /**
   * Operador tipado (property/contactField). Prefira em vez de valueMatch.
   * @return op
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOp() {
    return op;
  }


  @JsonProperty(value = JSON_PROPERTY_OP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOp(@javax.annotation.Nullable String op) {
    this.op = op;
  }


  public NtfContactSegmentRule valueMatch(@javax.annotation.Nullable ValueMatchEnum valueMatch) {
    this.valueMatch = valueMatch;
    return this;
  }

  /**
   * Legado para property STRING. Preferir op.
   * @return valueMatch
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE_MATCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ValueMatchEnum getValueMatch() {
    return valueMatch;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE_MATCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValueMatch(@javax.annotation.Nullable ValueMatchEnum valueMatch) {
    this.valueMatch = valueMatch;
  }


  public NtfContactSegmentRule ignoreCase(@javax.annotation.Nullable Boolean ignoreCase) {
    this.ignoreCase = ignoreCase;
    return this;
  }

  /**
   * Get ignoreCase
   * @return ignoreCase
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IGNORE_CASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIgnoreCase() {
    return ignoreCase;
  }


  @JsonProperty(value = JSON_PROPERTY_IGNORE_CASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIgnoreCase(@javax.annotation.Nullable Boolean ignoreCase) {
    this.ignoreCase = ignoreCase;
  }


  public NtfContactSegmentRule field(@javax.annotation.Nullable FieldEnum field) {
    this.field = field;
    return this;
  }

  /**
   * Campo de plataforma quando type&#x3D;contactField
   * @return field
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIELD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FieldEnum getField() {
    return field;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setField(@javax.annotation.Nullable FieldEnum field) {
    this.field = field;
  }


  public NtfContactSegmentRule topicId(@javax.annotation.Nullable String topicId) {
    this.topicId = topicId;
    return this;
  }

  /**
   * Obrigatorio quando type&#x3D;topic
   * @return topicId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOPIC_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTopicId() {
    return topicId;
  }


  @JsonProperty(value = JSON_PROPERTY_TOPIC_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopicId(@javax.annotation.Nullable String topicId) {
    this.topicId = topicId;
  }


  public NtfContactSegmentRule subscribed(@javax.annotation.Nullable Boolean subscribed) {
    this.subscribed = subscribed;
    return this;
  }

  /**
   * Quando type&#x3D;topic
   * @return subscribed
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBSCRIBED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSubscribed() {
    return subscribed;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBSCRIBED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubscribed(@javax.annotation.Nullable Boolean subscribed) {
    this.subscribed = subscribed;
  }


  /**
   * Return true if this NtfContact_SegmentRule object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfContactSegmentRule ntfContactSegmentRule = (NtfContactSegmentRule) o;
    return Objects.equals(this.type, ntfContactSegmentRule.type) &&
        Objects.equals(this.tagId, ntfContactSegmentRule.tagId) &&
        Objects.equals(this.key, ntfContactSegmentRule.key) &&
        Objects.equals(this.value, ntfContactSegmentRule.value) &&
        Objects.equals(this.op, ntfContactSegmentRule.op) &&
        Objects.equals(this.valueMatch, ntfContactSegmentRule.valueMatch) &&
        Objects.equals(this.ignoreCase, ntfContactSegmentRule.ignoreCase) &&
        Objects.equals(this.field, ntfContactSegmentRule.field) &&
        Objects.equals(this.topicId, ntfContactSegmentRule.topicId) &&
        Objects.equals(this.subscribed, ntfContactSegmentRule.subscribed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, tagId, key, value, op, valueMatch, ignoreCase, field, topicId, subscribed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfContactSegmentRule {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tagId: ").append(toIndentedString(tagId)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("    valueMatch: ").append(toIndentedString(valueMatch)).append("\n");
    sb.append("    ignoreCase: ").append(toIndentedString(ignoreCase)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    topicId: ").append(toIndentedString(topicId)).append("\n");
    sb.append("    subscribed: ").append(toIndentedString(subscribed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `tagId` to the URL query string
    if (getTagId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stagId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTagId()))));
    }

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(getValue().toUrlQueryString(prefix + "value" + suffix));
    }

    // add `op` to the URL query string
    if (getOp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sop%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOp()))));
    }

    // add `valueMatch` to the URL query string
    if (getValueMatch() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svalueMatch%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValueMatch()))));
    }

    // add `ignoreCase` to the URL query string
    if (getIgnoreCase() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%signoreCase%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIgnoreCase()))));
    }

    // add `field` to the URL query string
    if (getField() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfield%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getField()))));
    }

    // add `topicId` to the URL query string
    if (getTopicId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stopicId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTopicId()))));
    }

    // add `subscribed` to the URL query string
    if (getSubscribed() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubscribed%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubscribed()))));
    }

    return joiner.toString();
  }
}

