/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.notifique.sdk.ApiClient;
/**
 * NtfPlatformUsageEntry
 */
@JsonPropertyOrder({
  NtfPlatformUsageEntry.JSON_PROPERTY_ID,
  NtfPlatformUsageEntry.JSON_PROPERTY_AT,
  NtfPlatformUsageEntry.JSON_PROPERTY_TYPE,
  NtfPlatformUsageEntry.JSON_PROPERTY_DESCRIPTION,
  NtfPlatformUsageEntry.JSON_PROPERTY_CHARGED_AS,
  NtfPlatformUsageEntry.JSON_PROPERTY_DIRECTION,
  NtfPlatformUsageEntry.JSON_PROPERTY_CHARGE_AMOUNT,
  NtfPlatformUsageEntry.JSON_PROPERTY_CORRELATION_ID,
  NtfPlatformUsageEntry.JSON_PROPERTY_API_KEY_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfPlatformUsageEntry {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_AT = "at";
  @javax.annotation.Nullable
  private OffsetDateTime at;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  /**
   * Gets or Sets chargedAs
   */
  public enum ChargedAsEnum {
    CREDITS(String.valueOf("credits")),
    
    PREPAID(String.valueOf("prepaid"));

    private String value;

    ChargedAsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChargedAsEnum fromValue(String value) {
      for (ChargedAsEnum b : ChargedAsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CHARGED_AS = "chargedAs";
  @javax.annotation.Nullable
  private ChargedAsEnum chargedAs;

  /**
   * Gets or Sets direction
   */
  public enum DirectionEnum {
    CREDIT(String.valueOf("CREDIT")),
    
    DEBIT(String.valueOf("DEBIT"));

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DirectionEnum fromValue(String value) {
      for (DirectionEnum b : DirectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DIRECTION = "direction";
  @javax.annotation.Nullable
  private DirectionEnum direction;

  public static final String JSON_PROPERTY_CHARGE_AMOUNT = "chargeAmount";
  @javax.annotation.Nullable
  private BigDecimal chargeAmount;

  public static final String JSON_PROPERTY_CORRELATION_ID = "correlationId";
  @javax.annotation.Nullable
  private String correlationId;

  public static final String JSON_PROPERTY_API_KEY_ID = "apiKeyId";
  @javax.annotation.Nullable
  private String apiKeyId;

  public NtfPlatformUsageEntry() { 
  }

  public NtfPlatformUsageEntry id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public NtfPlatformUsageEntry at(@javax.annotation.Nullable OffsetDateTime at) {
    this.at = at;
    return this;
  }

  /**
   * Get at
   * @return at
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getAt() {
    return at;
  }


  @JsonProperty(value = JSON_PROPERTY_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAt(@javax.annotation.Nullable OffsetDateTime at) {
    this.at = at;
  }


  public NtfPlatformUsageEntry type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public NtfPlatformUsageEntry description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public NtfPlatformUsageEntry chargedAs(@javax.annotation.Nullable ChargedAsEnum chargedAs) {
    this.chargedAs = chargedAs;
    return this;
  }

  /**
   * Get chargedAs
   * @return chargedAs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHARGED_AS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ChargedAsEnum getChargedAs() {
    return chargedAs;
  }


  @JsonProperty(value = JSON_PROPERTY_CHARGED_AS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargedAs(@javax.annotation.Nullable ChargedAsEnum chargedAs) {
    this.chargedAs = chargedAs;
  }


  public NtfPlatformUsageEntry direction(@javax.annotation.Nullable DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   * @return direction
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIRECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DirectionEnum getDirection() {
    return direction;
  }


  @JsonProperty(value = JSON_PROPERTY_DIRECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirection(@javax.annotation.Nullable DirectionEnum direction) {
    this.direction = direction;
  }


  public NtfPlatformUsageEntry chargeAmount(@javax.annotation.Nullable BigDecimal chargeAmount) {
    this.chargeAmount = chargeAmount;
    return this;
  }

  /**
   * Get chargeAmount
   * @return chargeAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHARGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getChargeAmount() {
    return chargeAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_CHARGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargeAmount(@javax.annotation.Nullable BigDecimal chargeAmount) {
    this.chargeAmount = chargeAmount;
  }


  public NtfPlatformUsageEntry correlationId(@javax.annotation.Nullable String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

  /**
   * Get correlationId
   * @return correlationId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CORRELATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCorrelationId() {
    return correlationId;
  }


  @JsonProperty(value = JSON_PROPERTY_CORRELATION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorrelationId(@javax.annotation.Nullable String correlationId) {
    this.correlationId = correlationId;
  }


  public NtfPlatformUsageEntry apiKeyId(@javax.annotation.Nullable String apiKeyId) {
    this.apiKeyId = apiKeyId;
    return this;
  }

  /**
   * Get apiKeyId
   * @return apiKeyId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_API_KEY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getApiKeyId() {
    return apiKeyId;
  }


  @JsonProperty(value = JSON_PROPERTY_API_KEY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiKeyId(@javax.annotation.Nullable String apiKeyId) {
    this.apiKeyId = apiKeyId;
  }


  /**
   * Return true if this NtfPlatform_UsageEntry object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfPlatformUsageEntry ntfPlatformUsageEntry = (NtfPlatformUsageEntry) o;
    return Objects.equals(this.id, ntfPlatformUsageEntry.id) &&
        Objects.equals(this.at, ntfPlatformUsageEntry.at) &&
        Objects.equals(this.type, ntfPlatformUsageEntry.type) &&
        Objects.equals(this.description, ntfPlatformUsageEntry.description) &&
        Objects.equals(this.chargedAs, ntfPlatformUsageEntry.chargedAs) &&
        Objects.equals(this.direction, ntfPlatformUsageEntry.direction) &&
        Objects.equals(this.chargeAmount, ntfPlatformUsageEntry.chargeAmount) &&
        Objects.equals(this.correlationId, ntfPlatformUsageEntry.correlationId) &&
        Objects.equals(this.apiKeyId, ntfPlatformUsageEntry.apiKeyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, at, type, description, chargedAs, direction, chargeAmount, correlationId, apiKeyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfPlatformUsageEntry {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    chargedAs: ").append(toIndentedString(chargedAs)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    chargeAmount: ").append(toIndentedString(chargeAmount)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    apiKeyId: ").append(toIndentedString(apiKeyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `at` to the URL query string
    if (getAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sat%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAt()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `chargedAs` to the URL query string
    if (getChargedAs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schargedAs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChargedAs()))));
    }

    // add `direction` to the URL query string
    if (getDirection() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdirection%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDirection()))));
    }

    // add `chargeAmount` to the URL query string
    if (getChargeAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schargeAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChargeAmount()))));
    }

    // add `correlationId` to the URL query string
    if (getCorrelationId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scorrelationId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCorrelationId()))));
    }

    // add `apiKeyId` to the URL query string
    if (getApiKeyId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sapiKeyId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getApiKeyId()))));
    }

    return joiner.toString();
  }
}

