/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.notifique.sdk.ApiClient;
/**
 * NtfTgCreateTelegramInstanceRequest
 */
@JsonPropertyOrder({
  NtfTgCreateTelegramInstanceRequest.JSON_PROPERTY_NAME,
  NtfTgCreateTelegramInstanceRequest.JSON_PROPERTY_MODE,
  NtfTgCreateTelegramInstanceRequest.JSON_PROPERTY_BOT_TOKEN,
  NtfTgCreateTelegramInstanceRequest.JSON_PROPERTY_ACCEPT_USER_TERMS,
  NtfTgCreateTelegramInstanceRequest.JSON_PROPERTY_TERMS_VERSION,
  NtfTgCreateTelegramInstanceRequest.JSON_PROPERTY_GENERATE_SHAREABLE_LINK
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfTgCreateTelegramInstanceRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  /**
   * **&#x60;BOT&#x60;**: robô com token. **&#x60;USER&#x60;**: conta pessoal/profissional com login por QR.
   */
  public enum ModeEnum {
    BOT(String.valueOf("BOT")),
    
    USER(String.valueOf("USER"));

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MODE = "mode";
  @javax.annotation.Nonnull
  private ModeEnum mode;

  public static final String JSON_PROPERTY_BOT_TOKEN = "botToken";
  @javax.annotation.Nullable
  private String botToken;

  public static final String JSON_PROPERTY_ACCEPT_USER_TERMS = "acceptUserTerms";
  @javax.annotation.Nullable
  private Boolean acceptUserTerms;

  public static final String JSON_PROPERTY_TERMS_VERSION = "termsVersion";
  @javax.annotation.Nullable
  private String termsVersion;

  public static final String JSON_PROPERTY_GENERATE_SHAREABLE_LINK = "generateShareableLink";
  @javax.annotation.Nullable
  private Boolean generateShareableLink = false;

  public NtfTgCreateTelegramInstanceRequest() { 
  }

  public NtfTgCreateTelegramInstanceRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Nome para identificar esta conexão no painel.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public NtfTgCreateTelegramInstanceRequest mode(@javax.annotation.Nonnull ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * **&#x60;BOT&#x60;**: robô com token. **&#x60;USER&#x60;**: conta pessoal/profissional com login por QR.
   * @return mode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModeEnum getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMode(@javax.annotation.Nonnull ModeEnum mode) {
    this.mode = mode;
  }


  public NtfTgCreateTelegramInstanceRequest botToken(@javax.annotation.Nullable String botToken) {
    this.botToken = botToken;
    return this;
  }

  /**
   * Token do bot (obrigatório quando &#x60;mode&#x60; é BOT).
   * @return botToken
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BOT_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBotToken() {
    return botToken;
  }


  @JsonProperty(value = JSON_PROPERTY_BOT_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBotToken(@javax.annotation.Nullable String botToken) {
    this.botToken = botToken;
  }


  public NtfTgCreateTelegramInstanceRequest acceptUserTerms(@javax.annotation.Nullable Boolean acceptUserTerms) {
    this.acceptUserTerms = acceptUserTerms;
    return this;
  }

  /**
   * Obrigatório &#x60;true&#x60; no modo USER — confirma que você entende as regras de automação.
   * @return acceptUserTerms
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCEPT_USER_TERMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAcceptUserTerms() {
    return acceptUserTerms;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCEPT_USER_TERMS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcceptUserTerms(@javax.annotation.Nullable Boolean acceptUserTerms) {
    this.acceptUserTerms = acceptUserTerms;
  }


  public NtfTgCreateTelegramInstanceRequest termsVersion(@javax.annotation.Nullable String termsVersion) {
    this.termsVersion = termsVersion;
    return this;
  }

  /**
   * Opcional. Rótulo da versão dos termos aceitos no modo **USER** (ex.: &#x60;2026-04&#x60; ou &#x60;v2&#x60;), usado só para registro e auditoria. Se omitido, o servidor grava um valor padrão (&#x60;v1&#x60;). Não altera o funcionamento da API.
   * @return termsVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TERMS_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTermsVersion() {
    return termsVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_TERMS_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTermsVersion(@javax.annotation.Nullable String termsVersion) {
    this.termsVersion = termsVersion;
  }


  public NtfTgCreateTelegramInstanceRequest generateShareableLink(@javax.annotation.Nullable Boolean generateShareableLink) {
    this.generateShareableLink = generateShareableLink;
    return this;
  }

  /**
   * Gera um link para outra pessoa concluir o login. Omita para receber o QR na resposta.
   * @return generateShareableLink
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GENERATE_SHAREABLE_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getGenerateShareableLink() {
    return generateShareableLink;
  }


  @JsonProperty(value = JSON_PROPERTY_GENERATE_SHAREABLE_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenerateShareableLink(@javax.annotation.Nullable Boolean generateShareableLink) {
    this.generateShareableLink = generateShareableLink;
  }


  /**
   * Return true if this NtfTg_CreateTelegramInstanceRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfTgCreateTelegramInstanceRequest ntfTgCreateTelegramInstanceRequest = (NtfTgCreateTelegramInstanceRequest) o;
    return Objects.equals(this.name, ntfTgCreateTelegramInstanceRequest.name) &&
        Objects.equals(this.mode, ntfTgCreateTelegramInstanceRequest.mode) &&
        Objects.equals(this.botToken, ntfTgCreateTelegramInstanceRequest.botToken) &&
        Objects.equals(this.acceptUserTerms, ntfTgCreateTelegramInstanceRequest.acceptUserTerms) &&
        Objects.equals(this.termsVersion, ntfTgCreateTelegramInstanceRequest.termsVersion) &&
        Objects.equals(this.generateShareableLink, ntfTgCreateTelegramInstanceRequest.generateShareableLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, mode, botToken, acceptUserTerms, termsVersion, generateShareableLink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfTgCreateTelegramInstanceRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    botToken: ").append(toIndentedString(botToken)).append("\n");
    sb.append("    acceptUserTerms: ").append(toIndentedString(acceptUserTerms)).append("\n");
    sb.append("    termsVersion: ").append(toIndentedString(termsVersion)).append("\n");
    sb.append("    generateShareableLink: ").append(toIndentedString(generateShareableLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `mode` to the URL query string
    if (getMode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMode()))));
    }

    // add `botToken` to the URL query string
    if (getBotToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbotToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBotToken()))));
    }

    // add `acceptUserTerms` to the URL query string
    if (getAcceptUserTerms() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sacceptUserTerms%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAcceptUserTerms()))));
    }

    // add `termsVersion` to the URL query string
    if (getTermsVersion() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stermsVersion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTermsVersion()))));
    }

    // add `generateShareableLink` to the URL query string
    if (getGenerateShareableLink() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgenerateShareableLink%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGenerateShareableLink()))));
    }

    return joiner.toString();
  }
}

