/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.notifique.sdk.ApiClient;
/**
 * Dados para pareamento: QR em base64, code, pairingCode e count (UNOFFICIAL); ou status do provider oficial (OFFICIAL*).
 */
@JsonPropertyOrder({
  NtfWaCreateInstanceResponseDataConnection.JSON_PROPERTY_PAIRING_CODE,
  NtfWaCreateInstanceResponseDataConnection.JSON_PROPERTY_CODE,
  NtfWaCreateInstanceResponseDataConnection.JSON_PROPERTY_BASE64,
  NtfWaCreateInstanceResponseDataConnection.JSON_PROPERTY_COUNT,
  NtfWaCreateInstanceResponseDataConnection.JSON_PROPERTY_STATUS,
  NtfWaCreateInstanceResponseDataConnection.JSON_PROPERTY_METHOD,
  NtfWaCreateInstanceResponseDataConnection.JSON_PROPERTY_PHONE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfWaCreateInstanceResponseDataConnection {
  public static final String JSON_PROPERTY_PAIRING_CODE = "pairingCode";
  @javax.annotation.Nullable
  private String pairingCode;

  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_BASE64 = "base64";
  @javax.annotation.Nullable
  private String base64;

  public static final String JSON_PROPERTY_COUNT = "count";
  @javax.annotation.Nullable
  private Integer count;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_METHOD = "method";
  @javax.annotation.Nullable
  private String method;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  @javax.annotation.Nullable
  private String phoneNumber;

  public NtfWaCreateInstanceResponseDataConnection() { 
  }

  public NtfWaCreateInstanceResponseDataConnection pairingCode(@javax.annotation.Nullable String pairingCode) {
    this.pairingCode = pairingCode;
    return this;
  }

  /**
   * Código de pareamento (quando disponível).
   * @return pairingCode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAIRING_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPairingCode() {
    return pairingCode;
  }


  @JsonProperty(value = JSON_PROPERTY_PAIRING_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPairingCode(@javax.annotation.Nullable String pairingCode) {
    this.pairingCode = pairingCode;
  }


  public NtfWaCreateInstanceResponseDataConnection code(@javax.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  /**
   * Código interno de conexão.
   * @return code
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public NtfWaCreateInstanceResponseDataConnection base64(@javax.annotation.Nullable String base64) {
    this.base64 = base64;
    return this;
  }

  /**
   * Imagem do QR code em Data URL (ex.: data:image/png;base64,...). Use para exibir o QR (ex.: &lt;img src&#x3D;\&quot;connection.base64\&quot; /&gt;).
   * @return base64
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BASE64, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBase64() {
    return base64;
  }


  @JsonProperty(value = JSON_PROPERTY_BASE64, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBase64(@javax.annotation.Nullable String base64) {
    this.base64 = base64;
  }


  public NtfWaCreateInstanceResponseDataConnection count(@javax.annotation.Nullable Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Contador do QR/geração.
   * @return count
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getCount() {
    return count;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCount(@javax.annotation.Nullable Integer count) {
    this.count = count;
  }


  public NtfWaCreateInstanceResponseDataConnection status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public NtfWaCreateInstanceResponseDataConnection method(@javax.annotation.Nullable String method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@javax.annotation.Nullable String method) {
    this.method = method;
  }


  public NtfWaCreateInstanceResponseDataConnection phoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  /**
   * Return true if this NtfWa_CreateInstanceResponse_data_connection object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfWaCreateInstanceResponseDataConnection ntfWaCreateInstanceResponseDataConnection = (NtfWaCreateInstanceResponseDataConnection) o;
    return Objects.equals(this.pairingCode, ntfWaCreateInstanceResponseDataConnection.pairingCode) &&
        Objects.equals(this.code, ntfWaCreateInstanceResponseDataConnection.code) &&
        Objects.equals(this.base64, ntfWaCreateInstanceResponseDataConnection.base64) &&
        Objects.equals(this.count, ntfWaCreateInstanceResponseDataConnection.count) &&
        Objects.equals(this.status, ntfWaCreateInstanceResponseDataConnection.status) &&
        Objects.equals(this.method, ntfWaCreateInstanceResponseDataConnection.method) &&
        Objects.equals(this.phoneNumber, ntfWaCreateInstanceResponseDataConnection.phoneNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pairingCode, code, base64, count, status, method, phoneNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfWaCreateInstanceResponseDataConnection {\n");
    sb.append("    pairingCode: ").append(toIndentedString(pairingCode)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    base64: ").append(toIndentedString(base64)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `pairingCode` to the URL query string
    if (getPairingCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spairingCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPairingCode()))));
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `base64` to the URL query string
    if (getBase64() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbase64%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBase64()))));
    }

    // add `count` to the URL query string
    if (getCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCount()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMethod()))));
    }

    // add `phoneNumber` to the URL query string
    if (getPhoneNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphoneNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhoneNumber()))));
    }

    return joiner.toString();
  }
}

