// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// NtfAddonsFormConfirmEnvelopeData
    /// </summary>
    public partial class NtfAddonsFormConfirmEnvelopeData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NtfAddonsFormConfirmEnvelopeData" /> class.
        /// </summary>
        /// <param name="subscriptionId">subscriptionId</param>
        /// <param name="formId">formId</param>
        /// <param name="status">status</param>
        /// <param name="confirmedAt">confirmedAt</param>
        /// <param name="queuePosition">queuePosition</param>
        /// <param name="alreadyConfirmed">alreadyConfirmed</param>
        [JsonConstructor]
        public NtfAddonsFormConfirmEnvelopeData(string subscriptionId, string formId, string status, DateTime confirmedAt, Option<int?> queuePosition = default, Option<bool?> alreadyConfirmed = default)
        {
            SubscriptionId = subscriptionId;
            FormId = formId;
            Status = status;
            ConfirmedAt = confirmedAt;
            QueuePositionOption = queuePosition;
            AlreadyConfirmedOption = alreadyConfirmed;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets SubscriptionId
        /// </summary>
        [JsonPropertyName("subscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// Gets or Sets FormId
        /// </summary>
        [JsonPropertyName("formId")]
        public string FormId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets ConfirmedAt
        /// </summary>
        [JsonPropertyName("confirmedAt")]
        public DateTime ConfirmedAt { get; set; }

        /// <summary>
        /// Used to track the state of QueuePosition
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> QueuePositionOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueuePosition
        /// </summary>
        [JsonPropertyName("queuePosition")]
        public int? QueuePosition { get { return this.QueuePositionOption.Value; } set { this.QueuePositionOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlreadyConfirmed
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AlreadyConfirmedOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlreadyConfirmed
        /// </summary>
        [JsonPropertyName("alreadyConfirmed")]
        public bool? AlreadyConfirmed { get { return this.AlreadyConfirmedOption.Value; } set { this.AlreadyConfirmedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NtfAddonsFormConfirmEnvelopeData {\n");
            sb.Append("  SubscriptionId: ").Append(SubscriptionId).Append("\n");
            sb.Append("  FormId: ").Append(FormId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ConfirmedAt: ").Append(ConfirmedAt).Append("\n");
            sb.Append("  QueuePosition: ").Append(QueuePosition).Append("\n");
            sb.Append("  AlreadyConfirmed: ").Append(AlreadyConfirmed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NtfAddonsFormConfirmEnvelopeData" />
    /// </summary>
    public partial class NtfAddonsFormConfirmEnvelopeDataJsonConverter : JsonConverter<NtfAddonsFormConfirmEnvelopeData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NtfAddonsFormConfirmEnvelopeDataJsonConverter" /> class.
        /// </summary>
        public NtfAddonsFormConfirmEnvelopeDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ConfirmedAt
        /// </summary>
        public string ConfirmedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NtfAddonsFormConfirmEnvelopeData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NtfAddonsFormConfirmEnvelopeData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> subscriptionId = default;
            Option<string?> formId = default;
            Option<string?> status = default;
            Option<DateTime?> confirmedAt = default;
            Option<int?> queuePosition = default;
            Option<bool?> alreadyConfirmed = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "subscriptionId":
                            subscriptionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "formId":
                            formId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "confirmedAt":
                            confirmedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "queuePosition":
                            queuePosition = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "alreadyConfirmed":
                            alreadyConfirmed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!subscriptionId.IsSet)
                throw new ArgumentException("Property is required for class NtfAddonsFormConfirmEnvelopeData.", nameof(subscriptionId));

            if (!formId.IsSet)
                throw new ArgumentException("Property is required for class NtfAddonsFormConfirmEnvelopeData.", nameof(formId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class NtfAddonsFormConfirmEnvelopeData.", nameof(status));

            if (!confirmedAt.IsSet)
                throw new ArgumentException("Property is required for class NtfAddonsFormConfirmEnvelopeData.", nameof(confirmedAt));

            if (subscriptionId.IsSet && subscriptionId.Value == null)
                throw new ArgumentNullException(nameof(subscriptionId), "Property is not nullable for class NtfAddonsFormConfirmEnvelopeData.");

            if (formId.IsSet && formId.Value == null)
                throw new ArgumentNullException(nameof(formId), "Property is not nullable for class NtfAddonsFormConfirmEnvelopeData.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class NtfAddonsFormConfirmEnvelopeData.");

            if (confirmedAt.IsSet && confirmedAt.Value == null)
                throw new ArgumentNullException(nameof(confirmedAt), "Property is not nullable for class NtfAddonsFormConfirmEnvelopeData.");

            if (queuePosition.IsSet && queuePosition.Value == null)
                throw new ArgumentNullException(nameof(queuePosition), "Property is not nullable for class NtfAddonsFormConfirmEnvelopeData.");

            if (alreadyConfirmed.IsSet && alreadyConfirmed.Value == null)
                throw new ArgumentNullException(nameof(alreadyConfirmed), "Property is not nullable for class NtfAddonsFormConfirmEnvelopeData.");

            return new NtfAddonsFormConfirmEnvelopeData(subscriptionId.Value!, formId.Value!, status.Value!, confirmedAt.Value!.Value!, queuePosition, alreadyConfirmed);
        }

        /// <summary>
        /// Serializes a <see cref="NtfAddonsFormConfirmEnvelopeData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfAddonsFormConfirmEnvelopeData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NtfAddonsFormConfirmEnvelopeData ntfAddonsFormConfirmEnvelopeData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ntfAddonsFormConfirmEnvelopeData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NtfAddonsFormConfirmEnvelopeData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfAddonsFormConfirmEnvelopeData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NtfAddonsFormConfirmEnvelopeData ntfAddonsFormConfirmEnvelopeData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ntfAddonsFormConfirmEnvelopeData.SubscriptionId == null)
                throw new ArgumentNullException(nameof(ntfAddonsFormConfirmEnvelopeData.SubscriptionId), "Property is required for class NtfAddonsFormConfirmEnvelopeData.");

            if (ntfAddonsFormConfirmEnvelopeData.FormId == null)
                throw new ArgumentNullException(nameof(ntfAddonsFormConfirmEnvelopeData.FormId), "Property is required for class NtfAddonsFormConfirmEnvelopeData.");

            if (ntfAddonsFormConfirmEnvelopeData.Status == null)
                throw new ArgumentNullException(nameof(ntfAddonsFormConfirmEnvelopeData.Status), "Property is required for class NtfAddonsFormConfirmEnvelopeData.");

            writer.WriteString("subscriptionId", ntfAddonsFormConfirmEnvelopeData.SubscriptionId);

            writer.WriteString("formId", ntfAddonsFormConfirmEnvelopeData.FormId);

            writer.WriteString("status", ntfAddonsFormConfirmEnvelopeData.Status);

            writer.WriteString("confirmedAt", ntfAddonsFormConfirmEnvelopeData.ConfirmedAt.ToString(ConfirmedAtFormat));

            if (ntfAddonsFormConfirmEnvelopeData.QueuePositionOption.IsSet)
                writer.WriteNumber("queuePosition", ntfAddonsFormConfirmEnvelopeData.QueuePositionOption.Value!.Value);

            if (ntfAddonsFormConfirmEnvelopeData.AlreadyConfirmedOption.IsSet)
                writer.WriteBoolean("alreadyConfirmed", ntfAddonsFormConfirmEnvelopeData.AlreadyConfirmedOption.Value!.Value);
        }
    }
}
