// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// NtfContactPutV1TagResponse
    /// </summary>
    public partial class NtfContactPutV1TagResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NtfContactPutV1TagResponse" /> class.
        /// </summary>
        /// <param name="success">success</param>
        /// <param name="data">data</param>
        [JsonConstructor]
        public NtfContactPutV1TagResponse(Option<bool?> success = default, Option<NtfContactTag?> data = default)
        {
            SuccessOption = success;
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Success
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SuccessOption { get; private set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [JsonPropertyName("success")]
        public bool? Success { get { return this.SuccessOption.Value; } set { this.SuccessOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NtfContactTag?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public NtfContactTag? Data { get { return this.DataOption.Value; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NtfContactPutV1TagResponse {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NtfContactPutV1TagResponse" />
    /// </summary>
    public partial class NtfContactPutV1TagResponseJsonConverter : JsonConverter<NtfContactPutV1TagResponse>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NtfContactPutV1TagResponseJsonConverter" /> class.
        /// </summary>
        public NtfContactPutV1TagResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NtfContactPutV1TagResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NtfContactPutV1TagResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<NtfContactTag?> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "data":
                            data = new Option<NtfContactTag?>(JsonSerializer.Deserialize<NtfContactTag>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class NtfContactPutV1TagResponse.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class NtfContactPutV1TagResponse.");

            return new NtfContactPutV1TagResponse(success, data);
        }

        /// <summary>
        /// Serializes a <see cref="NtfContactPutV1TagResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfContactPutV1TagResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NtfContactPutV1TagResponse ntfContactPutV1TagResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ntfContactPutV1TagResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NtfContactPutV1TagResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfContactPutV1TagResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NtfContactPutV1TagResponse ntfContactPutV1TagResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ntfContactPutV1TagResponse.DataOption.IsSet && ntfContactPutV1TagResponse.Data == null)
                throw new ArgumentNullException(nameof(ntfContactPutV1TagResponse.Data), "Property is required for class NtfContactPutV1TagResponse.");

            if (ntfContactPutV1TagResponse.SuccessOption.IsSet)
                writer.WriteBoolean("success", ntfContactPutV1TagResponse.SuccessOption.Value!.Value);

            if (ntfContactPutV1TagResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, ntfContactPutV1TagResponse.Data, jsonSerializerOptions);
            }
        }
    }
}
