// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// NtfPlatformDeletePaymentMethodResponseData
    /// </summary>
    public partial class NtfPlatformDeletePaymentMethodResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NtfPlatformDeletePaymentMethodResponseData" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="deleted">deleted</param>
        [JsonConstructor]
        public NtfPlatformDeletePaymentMethodResponseData(Option<string?> id = default, Option<bool?> deleted = default)
        {
            IdOption = id;
            DeletedOption = deleted;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Deleted
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DeletedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Deleted
        /// </summary>
        [JsonPropertyName("deleted")]
        public bool? Deleted { get { return this.DeletedOption.Value; } set { this.DeletedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NtfPlatformDeletePaymentMethodResponseData {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Deleted: ").Append(Deleted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NtfPlatformDeletePaymentMethodResponseData" />
    /// </summary>
    public partial class NtfPlatformDeletePaymentMethodResponseDataJsonConverter : JsonConverter<NtfPlatformDeletePaymentMethodResponseData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NtfPlatformDeletePaymentMethodResponseDataJsonConverter" /> class.
        /// </summary>
        public NtfPlatformDeletePaymentMethodResponseDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NtfPlatformDeletePaymentMethodResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NtfPlatformDeletePaymentMethodResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<bool?> deleted = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "deleted":
                            deleted = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class NtfPlatformDeletePaymentMethodResponseData.");

            if (deleted.IsSet && deleted.Value == null)
                throw new ArgumentNullException(nameof(deleted), "Property is not nullable for class NtfPlatformDeletePaymentMethodResponseData.");

            return new NtfPlatformDeletePaymentMethodResponseData(id, deleted);
        }

        /// <summary>
        /// Serializes a <see cref="NtfPlatformDeletePaymentMethodResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfPlatformDeletePaymentMethodResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NtfPlatformDeletePaymentMethodResponseData ntfPlatformDeletePaymentMethodResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ntfPlatformDeletePaymentMethodResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NtfPlatformDeletePaymentMethodResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfPlatformDeletePaymentMethodResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NtfPlatformDeletePaymentMethodResponseData ntfPlatformDeletePaymentMethodResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ntfPlatformDeletePaymentMethodResponseData.IdOption.IsSet && ntfPlatformDeletePaymentMethodResponseData.Id == null)
                throw new ArgumentNullException(nameof(ntfPlatformDeletePaymentMethodResponseData.Id), "Property is required for class NtfPlatformDeletePaymentMethodResponseData.");

            if (ntfPlatformDeletePaymentMethodResponseData.IdOption.IsSet)
                writer.WriteString("id", ntfPlatformDeletePaymentMethodResponseData.Id);

            if (ntfPlatformDeletePaymentMethodResponseData.DeletedOption.IsSet)
                writer.WriteBoolean("deleted", ntfPlatformDeletePaymentMethodResponseData.DeletedOption.Value!.Value);
        }
    }
}
