// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// NtfShortLinksAnalyticsPayload
    /// </summary>
    public partial class NtfShortLinksAnalyticsPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NtfShortLinksAnalyticsPayload" /> class.
        /// </summary>
        /// <param name="granularity">granularity</param>
        /// <param name="range">range</param>
        /// <param name="series">series</param>
        /// <param name="breakdown">breakdown</param>
        [JsonConstructor]
        public NtfShortLinksAnalyticsPayload(GranularityEnum granularity, NtfShortLinksAnalyticsPayloadRange range, List<NtfShortLinksAnalyticsBucket> series, NtfShortLinksAnalyticsPayloadBreakdown breakdown)
        {
            Granularity = granularity;
            Range = range;
            Series = series;
            Breakdown = breakdown;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Granularity
        /// </summary>
        public enum GranularityEnum
        {
            /// <summary>
            /// Enum Hour for value: hour
            /// </summary>
            Hour = 1,

            /// <summary>
            /// Enum Day for value: day
            /// </summary>
            Day = 2
        }

        /// <summary>
        /// Returns a <see cref="GranularityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static GranularityEnum GranularityEnumFromString(string value)
        {
            if (value.Equals("hour"))
                return GranularityEnum.Hour;

            if (value.Equals("day"))
                return GranularityEnum.Day;

            throw new NotImplementedException($"Could not convert value to type GranularityEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="GranularityEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GranularityEnum? GranularityEnumFromStringOrDefault(string value)
        {
            if (value.Equals("hour"))
                return GranularityEnum.Hour;

            if (value.Equals("day"))
                return GranularityEnum.Day;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="GranularityEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string GranularityEnumToJsonValue(GranularityEnum value)
        {
            if (value == GranularityEnum.Hour)
                return "hour";

            if (value == GranularityEnum.Day)
                return "day";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Granularity
        /// </summary>
        [JsonPropertyName("granularity")]
        public GranularityEnum Granularity { get; set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [JsonPropertyName("range")]
        public NtfShortLinksAnalyticsPayloadRange Range { get; set; }

        /// <summary>
        /// Gets or Sets Series
        /// </summary>
        [JsonPropertyName("series")]
        public List<NtfShortLinksAnalyticsBucket> Series { get; set; }

        /// <summary>
        /// Gets or Sets Breakdown
        /// </summary>
        [JsonPropertyName("breakdown")]
        public NtfShortLinksAnalyticsPayloadBreakdown Breakdown { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NtfShortLinksAnalyticsPayload {\n");
            sb.Append("  Granularity: ").Append(Granularity).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  Series: ").Append(Series).Append("\n");
            sb.Append("  Breakdown: ").Append(Breakdown).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NtfShortLinksAnalyticsPayload" />
    /// </summary>
    public partial class NtfShortLinksAnalyticsPayloadJsonConverter : JsonConverter<NtfShortLinksAnalyticsPayload>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NtfShortLinksAnalyticsPayloadJsonConverter" /> class.
        /// </summary>
        public NtfShortLinksAnalyticsPayloadJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NtfShortLinksAnalyticsPayload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NtfShortLinksAnalyticsPayload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<NtfShortLinksAnalyticsPayload.GranularityEnum?> granularity = default;
            Option<NtfShortLinksAnalyticsPayloadRange?> range = default;
            Option<List<NtfShortLinksAnalyticsBucket>?> series = default;
            Option<NtfShortLinksAnalyticsPayloadBreakdown?> breakdown = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "granularity":
                            string? granularityRawValue = utf8JsonReader.GetString();
                            if (granularityRawValue != null)
                            {
                                NtfShortLinksAnalyticsPayload.GranularityEnum? granularityValue = NtfShortLinksAnalyticsPayload.GranularityEnumFromStringOrDefault(granularityRawValue);
                                if (granularityValue == null)
                                    throw new JsonException();
                                granularity = new Option<NtfShortLinksAnalyticsPayload.GranularityEnum?>(granularityValue);
                            }
                            break;
                        case "range":
                            range = new Option<NtfShortLinksAnalyticsPayloadRange?>(JsonSerializer.Deserialize<NtfShortLinksAnalyticsPayloadRange>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "series":
                            series = new Option<List<NtfShortLinksAnalyticsBucket>?>(JsonSerializer.Deserialize<List<NtfShortLinksAnalyticsBucket>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "breakdown":
                            breakdown = new Option<NtfShortLinksAnalyticsPayloadBreakdown?>(JsonSerializer.Deserialize<NtfShortLinksAnalyticsPayloadBreakdown>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!granularity.IsSet)
                throw new ArgumentException("Property is required for class NtfShortLinksAnalyticsPayload.", nameof(granularity));

            if (!range.IsSet)
                throw new ArgumentException("Property is required for class NtfShortLinksAnalyticsPayload.", nameof(range));

            if (!series.IsSet)
                throw new ArgumentException("Property is required for class NtfShortLinksAnalyticsPayload.", nameof(series));

            if (!breakdown.IsSet)
                throw new ArgumentException("Property is required for class NtfShortLinksAnalyticsPayload.", nameof(breakdown));

            if (granularity.IsSet && granularity.Value == null)
                throw new ArgumentNullException(nameof(granularity), "Property is not nullable for class NtfShortLinksAnalyticsPayload.");

            if (range.IsSet && range.Value == null)
                throw new ArgumentNullException(nameof(range), "Property is not nullable for class NtfShortLinksAnalyticsPayload.");

            if (series.IsSet && series.Value == null)
                throw new ArgumentNullException(nameof(series), "Property is not nullable for class NtfShortLinksAnalyticsPayload.");

            if (breakdown.IsSet && breakdown.Value == null)
                throw new ArgumentNullException(nameof(breakdown), "Property is not nullable for class NtfShortLinksAnalyticsPayload.");

            return new NtfShortLinksAnalyticsPayload(granularity.Value!.Value!, range.Value!, series.Value!, breakdown.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="NtfShortLinksAnalyticsPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfShortLinksAnalyticsPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NtfShortLinksAnalyticsPayload ntfShortLinksAnalyticsPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ntfShortLinksAnalyticsPayload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NtfShortLinksAnalyticsPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfShortLinksAnalyticsPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NtfShortLinksAnalyticsPayload ntfShortLinksAnalyticsPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ntfShortLinksAnalyticsPayload.Range == null)
                throw new ArgumentNullException(nameof(ntfShortLinksAnalyticsPayload.Range), "Property is required for class NtfShortLinksAnalyticsPayload.");

            if (ntfShortLinksAnalyticsPayload.Series == null)
                throw new ArgumentNullException(nameof(ntfShortLinksAnalyticsPayload.Series), "Property is required for class NtfShortLinksAnalyticsPayload.");

            if (ntfShortLinksAnalyticsPayload.Breakdown == null)
                throw new ArgumentNullException(nameof(ntfShortLinksAnalyticsPayload.Breakdown), "Property is required for class NtfShortLinksAnalyticsPayload.");

            var granularityRawValue = NtfShortLinksAnalyticsPayload.GranularityEnumToJsonValue(ntfShortLinksAnalyticsPayload.Granularity);
            writer.WriteString("granularity", granularityRawValue);
            writer.WritePropertyName("range");
            JsonSerializer.Serialize(writer, ntfShortLinksAnalyticsPayload.Range, jsonSerializerOptions);
            writer.WritePropertyName("series");
            JsonSerializer.Serialize(writer, ntfShortLinksAnalyticsPayload.Series, jsonSerializerOptions);
            writer.WritePropertyName("breakdown");
            JsonSerializer.Serialize(writer, ntfShortLinksAnalyticsPayload.Breakdown, jsonSerializerOptions);
        }
    }
}
