// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// Corpo conforme &#x60;type&#x60;. **text:** &#x60;message&#x60; obrigatório (9–160 caracteres após variáveis). **template:** &#x60;templateId&#x60; e &#x60;variables&#x60;.
    /// </summary>
    public partial class NtfSmsSendSmsRequestPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NtfSmsSendSmsRequestPayload" /> class.
        /// </summary>
        /// <param name="message">Texto do SMS quando &#x60;type&#x60; é &#x60;text&#x60;. Suporta &#x60;{{variáveis}}&#x60;.</param>
        /// <param name="templateId">ID do template do workspace quando &#x60;type&#x60; é &#x60;template&#x60;.</param>
        /// <param name="variables">Valores para placeholders do template.</param>
        [JsonConstructor]
        public NtfSmsSendSmsRequestPayload(Option<string?> message = default, Option<string?> templateId = default, Option<Dictionary<string, string>?> variables = default)
        {
            MessageOption = message;
            TemplateIdOption = templateId;
            VariablesOption = variables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Texto do SMS quando &#x60;type&#x60; é &#x60;text&#x60;. Suporta &#x60;{{variáveis}}&#x60;.
        /// </summary>
        /// <value>Texto do SMS quando &#x60;type&#x60; é &#x60;text&#x60;. Suporta &#x60;{{variáveis}}&#x60;.</value>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TemplateIdOption { get; private set; }

        /// <summary>
        /// ID do template do workspace quando &#x60;type&#x60; é &#x60;template&#x60;.
        /// </summary>
        /// <value>ID do template do workspace quando &#x60;type&#x60; é &#x60;template&#x60;.</value>
        [JsonPropertyName("templateId")]
        public string? TemplateId { get { return this.TemplateIdOption.Value; } set { this.TemplateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Variables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> VariablesOption { get; private set; }

        /// <summary>
        /// Valores para placeholders do template.
        /// </summary>
        /// <value>Valores para placeholders do template.</value>
        [JsonPropertyName("variables")]
        public Dictionary<string, string>? Variables { get { return this.VariablesOption.Value; } set { this.VariablesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NtfSmsSendSmsRequestPayload {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Message (string) maxLength
            if (this.Message != null && this.Message.Length > 160)
            {
                yield return new ValidationResult("Invalid value for Message, length must be less than 160.", new [] { "Message" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NtfSmsSendSmsRequestPayload" />
    /// </summary>
    public partial class NtfSmsSendSmsRequestPayloadJsonConverter : JsonConverter<NtfSmsSendSmsRequestPayload>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NtfSmsSendSmsRequestPayloadJsonConverter" /> class.
        /// </summary>
        public NtfSmsSendSmsRequestPayloadJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NtfSmsSendSmsRequestPayload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NtfSmsSendSmsRequestPayload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> message = default;
            Option<string?> templateId = default;
            Option<Dictionary<string, string>?> variables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "templateId":
                            templateId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "variables":
                            variables = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class NtfSmsSendSmsRequestPayload.");

            if (templateId.IsSet && templateId.Value == null)
                throw new ArgumentNullException(nameof(templateId), "Property is not nullable for class NtfSmsSendSmsRequestPayload.");

            if (variables.IsSet && variables.Value == null)
                throw new ArgumentNullException(nameof(variables), "Property is not nullable for class NtfSmsSendSmsRequestPayload.");

            return new NtfSmsSendSmsRequestPayload(message, templateId, variables);
        }

        /// <summary>
        /// Serializes a <see cref="NtfSmsSendSmsRequestPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfSmsSendSmsRequestPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NtfSmsSendSmsRequestPayload ntfSmsSendSmsRequestPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ntfSmsSendSmsRequestPayload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NtfSmsSendSmsRequestPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfSmsSendSmsRequestPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NtfSmsSendSmsRequestPayload ntfSmsSendSmsRequestPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ntfSmsSendSmsRequestPayload.MessageOption.IsSet && ntfSmsSendSmsRequestPayload.Message == null)
                throw new ArgumentNullException(nameof(ntfSmsSendSmsRequestPayload.Message), "Property is required for class NtfSmsSendSmsRequestPayload.");

            if (ntfSmsSendSmsRequestPayload.TemplateIdOption.IsSet && ntfSmsSendSmsRequestPayload.TemplateId == null)
                throw new ArgumentNullException(nameof(ntfSmsSendSmsRequestPayload.TemplateId), "Property is required for class NtfSmsSendSmsRequestPayload.");

            if (ntfSmsSendSmsRequestPayload.VariablesOption.IsSet && ntfSmsSendSmsRequestPayload.Variables == null)
                throw new ArgumentNullException(nameof(ntfSmsSendSmsRequestPayload.Variables), "Property is required for class NtfSmsSendSmsRequestPayload.");

            if (ntfSmsSendSmsRequestPayload.MessageOption.IsSet)
                writer.WriteString("message", ntfSmsSendSmsRequestPayload.Message);

            if (ntfSmsSendSmsRequestPayload.TemplateIdOption.IsSet)
                writer.WriteString("templateId", ntfSmsSendSmsRequestPayload.TemplateId);

            if (ntfSmsSendSmsRequestPayload.VariablesOption.IsSet)
            {
                writer.WritePropertyName("variables");
                JsonSerializer.Serialize(writer, ntfSmsSendSmsRequestPayload.Variables, jsonSerializerOptions);
            }
        }
    }
}
