// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// Item da listagem de mensagens enviadas (campo interno: &#x60;id&#x60;).
    /// </summary>
    public partial class NtfTgMessageOutboundRow : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NtfTgMessageOutboundRow" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="instanceId">instanceId</param>
        /// <param name="to">to</param>
        /// <param name="toName">toName</param>
        /// <param name="type">type</param>
        /// <param name="payload">payload</param>
        /// <param name="status">status</param>
        /// <param name="externalId">externalId</param>
        /// <param name="telegramPeer">telegramPeer</param>
        /// <param name="metadata">metadata</param>
        /// <param name="scheduledAt">scheduledAt</param>
        /// <param name="sentAt">sentAt</param>
        /// <param name="deliveredAt">deliveredAt</param>
        /// <param name="readAt">readAt</param>
        /// <param name="failedAt">failedAt</param>
        /// <param name="errorMessage">errorMessage</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="events">events</param>
        [JsonConstructor]
        public NtfTgMessageOutboundRow(Option<string?> id = default, Option<string?> instanceId = default, Option<string?> to = default, Option<string?> toName = default, Option<string?> type = default, Option<Object?> payload = default, Option<string?> status = default, Option<string?> externalId = default, Option<string?> telegramPeer = default, Option<Object?> metadata = default, Option<DateTime?> scheduledAt = default, Option<DateTime?> sentAt = default, Option<DateTime?> deliveredAt = default, Option<DateTime?> readAt = default, Option<DateTime?> failedAt = default, Option<string?> errorMessage = default, Option<DateTime?> createdAt = default, Option<DateTime?> updatedAt = default, Option<List<NtfTgMessageOutboundRowEventsInner>?> events = default)
        {
            IdOption = id;
            InstanceIdOption = instanceId;
            ToOption = to;
            ToNameOption = toName;
            TypeOption = type;
            PayloadOption = payload;
            StatusOption = status;
            ExternalIdOption = externalId;
            TelegramPeerOption = telegramPeer;
            MetadataOption = metadata;
            ScheduledAtOption = scheduledAt;
            SentAtOption = sentAt;
            DeliveredAtOption = deliveredAt;
            ReadAtOption = readAt;
            FailedAtOption = failedAt;
            ErrorMessageOption = errorMessage;
            CreatedAtOption = createdAt;
            UpdatedAtOption = updatedAt;
            EventsOption = events;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstanceId
        /// </summary>
        [JsonPropertyName("instanceId")]
        public string? InstanceId { get { return this.InstanceIdOption.Value; } set { this.InstanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of To
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ToOption { get; private set; }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [JsonPropertyName("to")]
        public string? To { get { return this.ToOption.Value; } set { this.ToOption = new(value); } }

        /// <summary>
        /// Used to track the state of ToName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ToNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ToName
        /// </summary>
        [JsonPropertyName("toName")]
        public string? ToName { get { return this.ToNameOption.Value; } set { this.ToNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Payload
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> PayloadOption { get; private set; }

        /// <summary>
        /// Gets or Sets Payload
        /// </summary>
        [JsonPropertyName("payload")]
        public Object? Payload { get { return this.PayloadOption.Value; } set { this.PayloadOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get { return this.ExternalIdOption.Value; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TelegramPeer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TelegramPeerOption { get; private set; }

        /// <summary>
        /// Gets or Sets TelegramPeer
        /// </summary>
        [JsonPropertyName("telegramPeer")]
        public string? TelegramPeer { get { return this.TelegramPeerOption.Value; } set { this.TelegramPeerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> MetadataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [JsonPropertyName("metadata")]
        public Object? Metadata { get { return this.MetadataOption.Value; } set { this.MetadataOption = new(value); } }

        /// <summary>
        /// Used to track the state of ScheduledAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ScheduledAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ScheduledAt
        /// </summary>
        [JsonPropertyName("scheduledAt")]
        public DateTime? ScheduledAt { get { return this.ScheduledAtOption.Value; } set { this.ScheduledAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of SentAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> SentAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets SentAt
        /// </summary>
        [JsonPropertyName("sentAt")]
        public DateTime? SentAt { get { return this.SentAtOption.Value; } set { this.SentAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of DeliveredAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DeliveredAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeliveredAt
        /// </summary>
        [JsonPropertyName("deliveredAt")]
        public DateTime? DeliveredAt { get { return this.DeliveredAtOption.Value; } set { this.DeliveredAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReadAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ReadAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReadAt
        /// </summary>
        [JsonPropertyName("readAt")]
        public DateTime? ReadAt { get { return this.ReadAtOption.Value; } set { this.ReadAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of FailedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> FailedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets FailedAt
        /// </summary>
        [JsonPropertyName("failedAt")]
        public DateTime? FailedAt { get { return this.FailedAtOption.Value; } set { this.FailedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of ErrorMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [JsonPropertyName("errorMessage")]
        public string? ErrorMessage { get { return this.ErrorMessageOption.Value; } set { this.ErrorMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime? UpdatedAt { get { return this.UpdatedAtOption.Value; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Events
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<NtfTgMessageOutboundRowEventsInner>?> EventsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [JsonPropertyName("events")]
        public List<NtfTgMessageOutboundRowEventsInner>? Events { get { return this.EventsOption.Value; } set { this.EventsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NtfTgMessageOutboundRow {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  ToName: ").Append(ToName).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  TelegramPeer: ").Append(TelegramPeer).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  ScheduledAt: ").Append(ScheduledAt).Append("\n");
            sb.Append("  SentAt: ").Append(SentAt).Append("\n");
            sb.Append("  DeliveredAt: ").Append(DeliveredAt).Append("\n");
            sb.Append("  ReadAt: ").Append(ReadAt).Append("\n");
            sb.Append("  FailedAt: ").Append(FailedAt).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NtfTgMessageOutboundRow" />
    /// </summary>
    public partial class NtfTgMessageOutboundRowJsonConverter : JsonConverter<NtfTgMessageOutboundRow>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NtfTgMessageOutboundRowJsonConverter" /> class.
        /// </summary>
        public NtfTgMessageOutboundRowJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ScheduledAt
        /// </summary>
        public string ScheduledAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize SentAt
        /// </summary>
        public string SentAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DeliveredAt
        /// </summary>
        public string DeliveredAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ReadAt
        /// </summary>
        public string ReadAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize FailedAt
        /// </summary>
        public string FailedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NtfTgMessageOutboundRow" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NtfTgMessageOutboundRow Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> instanceId = default;
            Option<string?> to = default;
            Option<string?> toName = default;
            Option<string?> type = default;
            Option<Object?> payload = default;
            Option<string?> status = default;
            Option<string?> externalId = default;
            Option<string?> telegramPeer = default;
            Option<Object?> metadata = default;
            Option<DateTime?> scheduledAt = default;
            Option<DateTime?> sentAt = default;
            Option<DateTime?> deliveredAt = default;
            Option<DateTime?> readAt = default;
            Option<DateTime?> failedAt = default;
            Option<string?> errorMessage = default;
            Option<DateTime?> createdAt = default;
            Option<DateTime?> updatedAt = default;
            Option<List<NtfTgMessageOutboundRowEventsInner>?> events = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "instanceId":
                            instanceId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "to":
                            to = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "toName":
                            toName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "payload":
                            payload = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "telegramPeer":
                            telegramPeer = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "metadata":
                            metadata = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "scheduledAt":
                            scheduledAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "sentAt":
                            sentAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "deliveredAt":
                            deliveredAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "readAt":
                            readAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "failedAt":
                            failedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "errorMessage":
                            errorMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "events":
                            events = new Option<List<NtfTgMessageOutboundRowEventsInner>?>(JsonSerializer.Deserialize<List<NtfTgMessageOutboundRowEventsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (instanceId.IsSet && instanceId.Value == null)
                throw new ArgumentNullException(nameof(instanceId), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (toName.IsSet && toName.Value == null)
                throw new ArgumentNullException(nameof(toName), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (externalId.IsSet && externalId.Value == null)
                throw new ArgumentNullException(nameof(externalId), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (telegramPeer.IsSet && telegramPeer.Value == null)
                throw new ArgumentNullException(nameof(telegramPeer), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (scheduledAt.IsSet && scheduledAt.Value == null)
                throw new ArgumentNullException(nameof(scheduledAt), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (sentAt.IsSet && sentAt.Value == null)
                throw new ArgumentNullException(nameof(sentAt), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (deliveredAt.IsSet && deliveredAt.Value == null)
                throw new ArgumentNullException(nameof(deliveredAt), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (readAt.IsSet && readAt.Value == null)
                throw new ArgumentNullException(nameof(readAt), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (failedAt.IsSet && failedAt.Value == null)
                throw new ArgumentNullException(nameof(failedAt), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (errorMessage.IsSet && errorMessage.Value == null)
                throw new ArgumentNullException(nameof(errorMessage), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class NtfTgMessageOutboundRow.");

            if (events.IsSet && events.Value == null)
                throw new ArgumentNullException(nameof(events), "Property is not nullable for class NtfTgMessageOutboundRow.");

            return new NtfTgMessageOutboundRow(id, instanceId, to, toName, type, payload, status, externalId, telegramPeer, metadata, scheduledAt, sentAt, deliveredAt, readAt, failedAt, errorMessage, createdAt, updatedAt, events);
        }

        /// <summary>
        /// Serializes a <see cref="NtfTgMessageOutboundRow" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfTgMessageOutboundRow"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NtfTgMessageOutboundRow ntfTgMessageOutboundRow, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ntfTgMessageOutboundRow, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NtfTgMessageOutboundRow" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfTgMessageOutboundRow"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NtfTgMessageOutboundRow ntfTgMessageOutboundRow, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ntfTgMessageOutboundRow.IdOption.IsSet && ntfTgMessageOutboundRow.Id == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.Id), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.InstanceIdOption.IsSet && ntfTgMessageOutboundRow.InstanceId == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.InstanceId), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.ToOption.IsSet && ntfTgMessageOutboundRow.To == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.To), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.ToNameOption.IsSet && ntfTgMessageOutboundRow.ToName == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.ToName), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.TypeOption.IsSet && ntfTgMessageOutboundRow.Type == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.Type), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.PayloadOption.IsSet && ntfTgMessageOutboundRow.Payload == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.Payload), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.StatusOption.IsSet && ntfTgMessageOutboundRow.Status == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.Status), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.ExternalIdOption.IsSet && ntfTgMessageOutboundRow.ExternalId == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.ExternalId), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.TelegramPeerOption.IsSet && ntfTgMessageOutboundRow.TelegramPeer == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.TelegramPeer), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.ErrorMessageOption.IsSet && ntfTgMessageOutboundRow.ErrorMessage == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.ErrorMessage), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.EventsOption.IsSet && ntfTgMessageOutboundRow.Events == null)
                throw new ArgumentNullException(nameof(ntfTgMessageOutboundRow.Events), "Property is required for class NtfTgMessageOutboundRow.");

            if (ntfTgMessageOutboundRow.IdOption.IsSet)
                writer.WriteString("id", ntfTgMessageOutboundRow.Id);

            if (ntfTgMessageOutboundRow.InstanceIdOption.IsSet)
                writer.WriteString("instanceId", ntfTgMessageOutboundRow.InstanceId);

            if (ntfTgMessageOutboundRow.ToOption.IsSet)
                writer.WriteString("to", ntfTgMessageOutboundRow.To);

            if (ntfTgMessageOutboundRow.ToNameOption.IsSet)
                writer.WriteString("toName", ntfTgMessageOutboundRow.ToName);

            if (ntfTgMessageOutboundRow.TypeOption.IsSet)
                writer.WriteString("type", ntfTgMessageOutboundRow.Type);

            if (ntfTgMessageOutboundRow.PayloadOption.IsSet)
            {
                writer.WritePropertyName("payload");
                JsonSerializer.Serialize(writer, ntfTgMessageOutboundRow.Payload, jsonSerializerOptions);
            }
            if (ntfTgMessageOutboundRow.StatusOption.IsSet)
                writer.WriteString("status", ntfTgMessageOutboundRow.Status);

            if (ntfTgMessageOutboundRow.ExternalIdOption.IsSet)
                writer.WriteString("externalId", ntfTgMessageOutboundRow.ExternalId);

            if (ntfTgMessageOutboundRow.TelegramPeerOption.IsSet)
                writer.WriteString("telegramPeer", ntfTgMessageOutboundRow.TelegramPeer);

            if (ntfTgMessageOutboundRow.MetadataOption.IsSet)
                if (ntfTgMessageOutboundRow.MetadataOption.Value != null)
                {
                    writer.WritePropertyName("metadata");
                    JsonSerializer.Serialize(writer, ntfTgMessageOutboundRow.Metadata, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("metadata");
            if (ntfTgMessageOutboundRow.ScheduledAtOption.IsSet)
                writer.WriteString("scheduledAt", ntfTgMessageOutboundRow.ScheduledAtOption.Value!.Value.ToString(ScheduledAtFormat));

            if (ntfTgMessageOutboundRow.SentAtOption.IsSet)
                writer.WriteString("sentAt", ntfTgMessageOutboundRow.SentAtOption.Value!.Value.ToString(SentAtFormat));

            if (ntfTgMessageOutboundRow.DeliveredAtOption.IsSet)
                writer.WriteString("deliveredAt", ntfTgMessageOutboundRow.DeliveredAtOption.Value!.Value.ToString(DeliveredAtFormat));

            if (ntfTgMessageOutboundRow.ReadAtOption.IsSet)
                writer.WriteString("readAt", ntfTgMessageOutboundRow.ReadAtOption.Value!.Value.ToString(ReadAtFormat));

            if (ntfTgMessageOutboundRow.FailedAtOption.IsSet)
                writer.WriteString("failedAt", ntfTgMessageOutboundRow.FailedAtOption.Value!.Value.ToString(FailedAtFormat));

            if (ntfTgMessageOutboundRow.ErrorMessageOption.IsSet)
                writer.WriteString("errorMessage", ntfTgMessageOutboundRow.ErrorMessage);

            if (ntfTgMessageOutboundRow.CreatedAtOption.IsSet)
                writer.WriteString("createdAt", ntfTgMessageOutboundRow.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));

            if (ntfTgMessageOutboundRow.UpdatedAtOption.IsSet)
                writer.WriteString("updatedAt", ntfTgMessageOutboundRow.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));

            if (ntfTgMessageOutboundRow.EventsOption.IsSet)
            {
                writer.WritePropertyName("events");
                JsonSerializer.Serialize(writer, ntfTgMessageOutboundRow.Events, jsonSerializerOptions);
            }
        }
    }
}
