// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// NtfWaSendWhatsAppMessageRequest
    /// </summary>
    public partial class NtfWaSendWhatsAppMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NtfWaSendWhatsAppMessageRequest" /> class.
        /// </summary>
        /// <param name="to">Destinatários: números com DDI (ex.: 5511999999999) ou JID de grupo (ex.: 120363295648424210@g.us). Uma mensagem por item.</param>
        /// <param name="type">Tipo da mensagem. Use &#x60;template&#x60; com &#x60;payload.templateId&#x60; para templates do workspace (oficial ou não oficial).</param>
        /// <param name="payload">payload</param>
        /// <param name="instanceId">ID da instância WhatsApp. Obrigatório se &#x60;sendingPoolId&#x60; não for informado. Não combine com &#x60;sendingPoolId&#x60;.</param>
        /// <param name="schedule">schedule</param>
        /// <param name="options">options</param>
        /// <param name="metadata">Metadados por envio, mesclados em &#x60;Message.metadata&#x60; (pares string→string). Respeite limites de payload.</param>
        /// <param name="sendingPoolId">ID do sending pool para balancear destinatários entre instâncias. Alternativa a &#x60;instanceId&#x60; (não use os dois).</param>
        /// <param name="localization">localization</param>
        /// <param name="i18n">Mapa locale → string ou objeto com chaves por campo (message, caption, …). Usado com localization.mode&#x3D;manual.</param>
        /// <param name="variables">Variáveis para substituir placeholders {{chave}} em payload.message, payload.caption e options.autoReplyText.</param>
        [JsonConstructor]
        public NtfWaSendWhatsAppMessageRequest(List<string> to, TypeEnum type, NtfWaSendWhatsAppMessageRequestPayload payload, Option<string?> instanceId = default, Option<NtfWaSendWhatsAppMessageRequestSchedule?> schedule = default, Option<NtfWaSendWhatsAppMessageRequestOptions?> options = default, Option<Dictionary<string, string>?> metadata = default, Option<string?> sendingPoolId = default, Option<NtfWaSendWhatsAppMessageRequestLocalization?> localization = default, Option<Dictionary<string, Object>?> i18n = default, Option<Dictionary<string, string>?> variables = default)
        {
            To = to;
            Type = type;
            Payload = payload;
            InstanceIdOption = instanceId;
            ScheduleOption = schedule;
            OptionsOption = options;
            MetadataOption = metadata;
            SendingPoolIdOption = sendingPoolId;
            LocalizationOption = localization;
            I18nOption = i18n;
            VariablesOption = variables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Tipo da mensagem. Use &#x60;template&#x60; com &#x60;payload.templateId&#x60; para templates do workspace (oficial ou não oficial).
        /// </summary>
        /// <value>Tipo da mensagem. Use &#x60;template&#x60; com &#x60;payload.templateId&#x60; para templates do workspace (oficial ou não oficial).</value>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Text for value: text
            /// </summary>
            Text = 1,

            /// <summary>
            /// Enum Image for value: image
            /// </summary>
            Image = 2,

            /// <summary>
            /// Enum Video for value: video
            /// </summary>
            Video = 3,

            /// <summary>
            /// Enum Audio for value: audio
            /// </summary>
            Audio = 4,

            /// <summary>
            /// Enum Document for value: document
            /// </summary>
            Document = 5,

            /// <summary>
            /// Enum Location for value: location
            /// </summary>
            Location = 6,

            /// <summary>
            /// Enum Contact for value: contact
            /// </summary>
            Contact = 7,

            /// <summary>
            /// Enum Buttons for value: buttons
            /// </summary>
            Buttons = 8,

            /// <summary>
            /// Enum List for value: list
            /// </summary>
            List = 9,

            /// <summary>
            /// Enum Carousel for value: carousel
            /// </summary>
            Carousel = 10,

            /// <summary>
            /// Enum Template for value: template
            /// </summary>
            Template = 11
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("text"))
                return TypeEnum.Text;

            if (value.Equals("image"))
                return TypeEnum.Image;

            if (value.Equals("video"))
                return TypeEnum.Video;

            if (value.Equals("audio"))
                return TypeEnum.Audio;

            if (value.Equals("document"))
                return TypeEnum.Document;

            if (value.Equals("location"))
                return TypeEnum.Location;

            if (value.Equals("contact"))
                return TypeEnum.Contact;

            if (value.Equals("buttons"))
                return TypeEnum.Buttons;

            if (value.Equals("list"))
                return TypeEnum.List;

            if (value.Equals("carousel"))
                return TypeEnum.Carousel;

            if (value.Equals("template"))
                return TypeEnum.Template;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("text"))
                return TypeEnum.Text;

            if (value.Equals("image"))
                return TypeEnum.Image;

            if (value.Equals("video"))
                return TypeEnum.Video;

            if (value.Equals("audio"))
                return TypeEnum.Audio;

            if (value.Equals("document"))
                return TypeEnum.Document;

            if (value.Equals("location"))
                return TypeEnum.Location;

            if (value.Equals("contact"))
                return TypeEnum.Contact;

            if (value.Equals("buttons"))
                return TypeEnum.Buttons;

            if (value.Equals("list"))
                return TypeEnum.List;

            if (value.Equals("carousel"))
                return TypeEnum.Carousel;

            if (value.Equals("template"))
                return TypeEnum.Template;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Text)
                return "text";

            if (value == TypeEnum.Image)
                return "image";

            if (value == TypeEnum.Video)
                return "video";

            if (value == TypeEnum.Audio)
                return "audio";

            if (value == TypeEnum.Document)
                return "document";

            if (value == TypeEnum.Location)
                return "location";

            if (value == TypeEnum.Contact)
                return "contact";

            if (value == TypeEnum.Buttons)
                return "buttons";

            if (value == TypeEnum.List)
                return "list";

            if (value == TypeEnum.Carousel)
                return "carousel";

            if (value == TypeEnum.Template)
                return "template";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Tipo da mensagem. Use &#x60;template&#x60; com &#x60;payload.templateId&#x60; para templates do workspace (oficial ou não oficial).
        /// </summary>
        /// <value>Tipo da mensagem. Use &#x60;template&#x60; com &#x60;payload.templateId&#x60; para templates do workspace (oficial ou não oficial).</value>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Destinatários: números com DDI (ex.: 5511999999999) ou JID de grupo (ex.: 120363295648424210@g.us). Uma mensagem por item.
        /// </summary>
        /// <value>Destinatários: números com DDI (ex.: 5511999999999) ou JID de grupo (ex.: 120363295648424210@g.us). Uma mensagem por item.</value>
        [JsonPropertyName("to")]
        public List<string> To { get; set; }

        /// <summary>
        /// Gets or Sets Payload
        /// </summary>
        [JsonPropertyName("payload")]
        public NtfWaSendWhatsAppMessageRequestPayload Payload { get; set; }

        /// <summary>
        /// Used to track the state of InstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstanceIdOption { get; private set; }

        /// <summary>
        /// ID da instância WhatsApp. Obrigatório se &#x60;sendingPoolId&#x60; não for informado. Não combine com &#x60;sendingPoolId&#x60;.
        /// </summary>
        /// <value>ID da instância WhatsApp. Obrigatório se &#x60;sendingPoolId&#x60; não for informado. Não combine com &#x60;sendingPoolId&#x60;.</value>
        [JsonPropertyName("instanceId")]
        public string? InstanceId { get { return this.InstanceIdOption.Value; } set { this.InstanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schedule
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NtfWaSendWhatsAppMessageRequestSchedule?> ScheduleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [JsonPropertyName("schedule")]
        public NtfWaSendWhatsAppMessageRequestSchedule? Schedule { get { return this.ScheduleOption.Value; } set { this.ScheduleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Options
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NtfWaSendWhatsAppMessageRequestOptions?> OptionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Options
        /// </summary>
        [JsonPropertyName("options")]
        public NtfWaSendWhatsAppMessageRequestOptions? Options { get { return this.OptionsOption.Value; } set { this.OptionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> MetadataOption { get; private set; }

        /// <summary>
        /// Metadados por envio, mesclados em &#x60;Message.metadata&#x60; (pares string→string). Respeite limites de payload.
        /// </summary>
        /// <value>Metadados por envio, mesclados em &#x60;Message.metadata&#x60; (pares string→string). Respeite limites de payload.</value>
        [JsonPropertyName("metadata")]
        public Dictionary<string, string>? Metadata { get { return this.MetadataOption.Value; } set { this.MetadataOption = new(value); } }

        /// <summary>
        /// Used to track the state of SendingPoolId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SendingPoolIdOption { get; private set; }

        /// <summary>
        /// ID do sending pool para balancear destinatários entre instâncias. Alternativa a &#x60;instanceId&#x60; (não use os dois).
        /// </summary>
        /// <value>ID do sending pool para balancear destinatários entre instâncias. Alternativa a &#x60;instanceId&#x60; (não use os dois).</value>
        [JsonPropertyName("sendingPoolId")]
        public string? SendingPoolId { get { return this.SendingPoolIdOption.Value; } set { this.SendingPoolIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Localization
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<NtfWaSendWhatsAppMessageRequestLocalization?> LocalizationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Localization
        /// </summary>
        [JsonPropertyName("localization")]
        public NtfWaSendWhatsAppMessageRequestLocalization? Localization { get { return this.LocalizationOption.Value; } set { this.LocalizationOption = new(value); } }

        /// <summary>
        /// Used to track the state of I18n
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Object>?> I18nOption { get; private set; }

        /// <summary>
        /// Mapa locale → string ou objeto com chaves por campo (message, caption, …). Usado com localization.mode&#x3D;manual.
        /// </summary>
        /// <value>Mapa locale → string ou objeto com chaves por campo (message, caption, …). Usado com localization.mode&#x3D;manual.</value>
        [JsonPropertyName("i18n")]
        public Dictionary<string, Object>? I18n { get { return this.I18nOption.Value; } set { this.I18nOption = new(value); } }

        /// <summary>
        /// Used to track the state of Variables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>?> VariablesOption { get; private set; }

        /// <summary>
        /// Variáveis para substituir placeholders {{chave}} em payload.message, payload.caption e options.autoReplyText.
        /// </summary>
        /// <value>Variáveis para substituir placeholders {{chave}} em payload.message, payload.caption e options.autoReplyText.</value>
        [JsonPropertyName("variables")]
        public Dictionary<string, string>? Variables { get { return this.VariablesOption.Value; } set { this.VariablesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NtfWaSendWhatsAppMessageRequest {\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  SendingPoolId: ").Append(SendingPoolId).Append("\n");
            sb.Append("  Localization: ").Append(Localization).Append("\n");
            sb.Append("  I18n: ").Append(I18n).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NtfWaSendWhatsAppMessageRequest" />
    /// </summary>
    public partial class NtfWaSendWhatsAppMessageRequestJsonConverter : JsonConverter<NtfWaSendWhatsAppMessageRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NtfWaSendWhatsAppMessageRequestJsonConverter" /> class.
        /// </summary>
        public NtfWaSendWhatsAppMessageRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NtfWaSendWhatsAppMessageRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NtfWaSendWhatsAppMessageRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> to = default;
            Option<NtfWaSendWhatsAppMessageRequest.TypeEnum?> type = default;
            Option<NtfWaSendWhatsAppMessageRequestPayload?> payload = default;
            Option<string?> instanceId = default;
            Option<NtfWaSendWhatsAppMessageRequestSchedule?> schedule = default;
            Option<NtfWaSendWhatsAppMessageRequestOptions?> options = default;
            Option<Dictionary<string, string>?> metadata = default;
            Option<string?> sendingPoolId = default;
            Option<NtfWaSendWhatsAppMessageRequestLocalization?> localization = default;
            Option<Dictionary<string, Object>?> i18n = default;
            Option<Dictionary<string, string>?> variables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "to":
                            to = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                            {
                                NtfWaSendWhatsAppMessageRequest.TypeEnum? typeValue = NtfWaSendWhatsAppMessageRequest.TypeEnumFromStringOrDefault(typeRawValue);
                                if (typeValue == null)
                                    throw new JsonException();
                                type = new Option<NtfWaSendWhatsAppMessageRequest.TypeEnum?>(typeValue);
                            }
                            break;
                        case "payload":
                            payload = new Option<NtfWaSendWhatsAppMessageRequestPayload?>(JsonSerializer.Deserialize<NtfWaSendWhatsAppMessageRequestPayload>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "instanceId":
                            instanceId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schedule":
                            schedule = new Option<NtfWaSendWhatsAppMessageRequestSchedule?>(JsonSerializer.Deserialize<NtfWaSendWhatsAppMessageRequestSchedule>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "options":
                            options = new Option<NtfWaSendWhatsAppMessageRequestOptions?>(JsonSerializer.Deserialize<NtfWaSendWhatsAppMessageRequestOptions>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "metadata":
                            metadata = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sendingPoolId":
                            sendingPoolId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "localization":
                            localization = new Option<NtfWaSendWhatsAppMessageRequestLocalization?>(JsonSerializer.Deserialize<NtfWaSendWhatsAppMessageRequestLocalization>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "i18n":
                            i18n = new Option<Dictionary<string, Object>?>(JsonSerializer.Deserialize<Dictionary<string, Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "variables":
                            variables = new Option<Dictionary<string, string>?>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class NtfWaSendWhatsAppMessageRequest.", nameof(to));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class NtfWaSendWhatsAppMessageRequest.", nameof(type));

            if (!payload.IsSet)
                throw new ArgumentException("Property is required for class NtfWaSendWhatsAppMessageRequest.", nameof(payload));

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (instanceId.IsSet && instanceId.Value == null)
                throw new ArgumentNullException(nameof(instanceId), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (schedule.IsSet && schedule.Value == null)
                throw new ArgumentNullException(nameof(schedule), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (options.IsSet && options.Value == null)
                throw new ArgumentNullException(nameof(options), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (metadata.IsSet && metadata.Value == null)
                throw new ArgumentNullException(nameof(metadata), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (sendingPoolId.IsSet && sendingPoolId.Value == null)
                throw new ArgumentNullException(nameof(sendingPoolId), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (localization.IsSet && localization.Value == null)
                throw new ArgumentNullException(nameof(localization), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (i18n.IsSet && i18n.Value == null)
                throw new ArgumentNullException(nameof(i18n), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            if (variables.IsSet && variables.Value == null)
                throw new ArgumentNullException(nameof(variables), "Property is not nullable for class NtfWaSendWhatsAppMessageRequest.");

            return new NtfWaSendWhatsAppMessageRequest(to.Value!, type.Value!.Value!, payload.Value!, instanceId, schedule, options, metadata, sendingPoolId, localization, i18n, variables);
        }

        /// <summary>
        /// Serializes a <see cref="NtfWaSendWhatsAppMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfWaSendWhatsAppMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NtfWaSendWhatsAppMessageRequest ntfWaSendWhatsAppMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, ntfWaSendWhatsAppMessageRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NtfWaSendWhatsAppMessageRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="ntfWaSendWhatsAppMessageRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NtfWaSendWhatsAppMessageRequest ntfWaSendWhatsAppMessageRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (ntfWaSendWhatsAppMessageRequest.To == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.To), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.Payload == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.Payload), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.InstanceIdOption.IsSet && ntfWaSendWhatsAppMessageRequest.InstanceId == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.InstanceId), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.ScheduleOption.IsSet && ntfWaSendWhatsAppMessageRequest.Schedule == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.Schedule), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.OptionsOption.IsSet && ntfWaSendWhatsAppMessageRequest.Options == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.Options), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.MetadataOption.IsSet && ntfWaSendWhatsAppMessageRequest.Metadata == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.Metadata), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.SendingPoolIdOption.IsSet && ntfWaSendWhatsAppMessageRequest.SendingPoolId == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.SendingPoolId), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.LocalizationOption.IsSet && ntfWaSendWhatsAppMessageRequest.Localization == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.Localization), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.I18nOption.IsSet && ntfWaSendWhatsAppMessageRequest.I18n == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.I18n), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            if (ntfWaSendWhatsAppMessageRequest.VariablesOption.IsSet && ntfWaSendWhatsAppMessageRequest.Variables == null)
                throw new ArgumentNullException(nameof(ntfWaSendWhatsAppMessageRequest.Variables), "Property is required for class NtfWaSendWhatsAppMessageRequest.");

            writer.WritePropertyName("to");
            JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.To, jsonSerializerOptions);
            var typeRawValue = NtfWaSendWhatsAppMessageRequest.TypeEnumToJsonValue(ntfWaSendWhatsAppMessageRequest.Type);
            writer.WriteString("type", typeRawValue);
            writer.WritePropertyName("payload");
            JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.Payload, jsonSerializerOptions);
            if (ntfWaSendWhatsAppMessageRequest.InstanceIdOption.IsSet)
                writer.WriteString("instanceId", ntfWaSendWhatsAppMessageRequest.InstanceId);

            if (ntfWaSendWhatsAppMessageRequest.ScheduleOption.IsSet)
            {
                writer.WritePropertyName("schedule");
                JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.Schedule, jsonSerializerOptions);
            }
            if (ntfWaSendWhatsAppMessageRequest.OptionsOption.IsSet)
            {
                writer.WritePropertyName("options");
                JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.Options, jsonSerializerOptions);
            }
            if (ntfWaSendWhatsAppMessageRequest.MetadataOption.IsSet)
            {
                writer.WritePropertyName("metadata");
                JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.Metadata, jsonSerializerOptions);
            }
            if (ntfWaSendWhatsAppMessageRequest.SendingPoolIdOption.IsSet)
                writer.WriteString("sendingPoolId", ntfWaSendWhatsAppMessageRequest.SendingPoolId);

            if (ntfWaSendWhatsAppMessageRequest.LocalizationOption.IsSet)
            {
                writer.WritePropertyName("localization");
                JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.Localization, jsonSerializerOptions);
            }
            if (ntfWaSendWhatsAppMessageRequest.I18nOption.IsSet)
            {
                writer.WritePropertyName("i18n");
                JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.I18n, jsonSerializerOptions);
            }
            if (ntfWaSendWhatsAppMessageRequest.VariablesOption.IsSet)
            {
                writer.WritePropertyName("variables");
                JsonSerializer.Serialize(writer, ntfWaSendWhatsAppMessageRequest.Variables, jsonSerializerOptions);
            }
        }
    }
}
