// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// TemplateSendRequestSchedule
    /// </summary>
    public partial class TemplateSendRequestSchedule : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateSendRequestSchedule" /> class.
        /// </summary>
        /// <param name="sendAt">sendAt</param>
        [JsonConstructor]
        public TemplateSendRequestSchedule(Option<DateTime?> sendAt = default)
        {
            SendAtOption = sendAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SendAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> SendAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets SendAt
        /// </summary>
        /* <example>2026-07-10T15:00:00.000Z</example> */
        [JsonPropertyName("sendAt")]
        public DateTime? SendAt { get { return this.SendAtOption.Value; } set { this.SendAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateSendRequestSchedule {\n");
            sb.Append("  SendAt: ").Append(SendAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TemplateSendRequestSchedule" />
    /// </summary>
    public partial class TemplateSendRequestScheduleJsonConverter : JsonConverter<TemplateSendRequestSchedule>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateSendRequestScheduleJsonConverter" /> class.
        /// </summary>
        public TemplateSendRequestScheduleJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize SendAt
        /// </summary>
        public string SendAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TemplateSendRequestSchedule" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TemplateSendRequestSchedule Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTime?> sendAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sendAt":
                            sendAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (sendAt.IsSet && sendAt.Value == null)
                throw new ArgumentNullException(nameof(sendAt), "Property is not nullable for class TemplateSendRequestSchedule.");

            return new TemplateSendRequestSchedule(sendAt);
        }

        /// <summary>
        /// Serializes a <see cref="TemplateSendRequestSchedule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="templateSendRequestSchedule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TemplateSendRequestSchedule templateSendRequestSchedule, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, templateSendRequestSchedule, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TemplateSendRequestSchedule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="templateSendRequestSchedule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TemplateSendRequestSchedule templateSendRequestSchedule, JsonSerializerOptions jsonSerializerOptions)
        {
            if (templateSendRequestSchedule.SendAtOption.IsSet)
                writer.WriteString("sendAt", templateSendRequestSchedule.SendAtOption.Value!.Value.ToString(SendAtFormat));
        }
    }
}
