// <auto-generated>
/*
 * Notifique API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Notifique.OpenApi.Models.Client;

namespace Notifique.OpenApi.Models.Model
{
    /// <summary>
    /// WorkspaceGetResponseData
    /// </summary>
    public partial class WorkspaceGetResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceGetResponseData" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="slug">slug</param>
        /// <param name="color">color</param>
        /// <param name="defaultInstanceId">defaultInstanceId</param>
        /// <param name="defaultEmailDomainId">defaultEmailDomainId</param>
        /// <param name="inboundSettings">inboundSettings</param>
        /// <param name="updatedAt">updatedAt</param>
        [JsonConstructor]
        public WorkspaceGetResponseData(Option<string?> id = default, Option<string?> name = default, Option<string?> slug = default, Option<string?> color = default, Option<string?> defaultInstanceId = default, Option<string?> defaultEmailDomainId = default, Option<InboundSettings?> inboundSettings = default, Option<DateTime?> updatedAt = default)
        {
            IdOption = id;
            NameOption = name;
            SlugOption = slug;
            ColorOption = color;
            DefaultInstanceIdOption = defaultInstanceId;
            DefaultEmailDomainIdOption = defaultEmailDomainId;
            InboundSettingsOption = inboundSettings;
            UpdatedAtOption = updatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Slug
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SlugOption { get; private set; }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [JsonPropertyName("slug")]
        public string? Slug { get { return this.SlugOption.Value; } set { this.SlugOption = new(value); } }

        /// <summary>
        /// Used to track the state of Color
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ColorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [JsonPropertyName("color")]
        public string? Color { get { return this.ColorOption.Value; } set { this.ColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of DefaultInstanceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DefaultInstanceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DefaultInstanceId
        /// </summary>
        [JsonPropertyName("defaultInstanceId")]
        public string? DefaultInstanceId { get { return this.DefaultInstanceIdOption.Value; } set { this.DefaultInstanceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of DefaultEmailDomainId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DefaultEmailDomainIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DefaultEmailDomainId
        /// </summary>
        [JsonPropertyName("defaultEmailDomainId")]
        public string? DefaultEmailDomainId { get { return this.DefaultEmailDomainIdOption.Value; } set { this.DefaultEmailDomainIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InboundSettings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<InboundSettings?> InboundSettingsOption { get; private set; }

        /// <summary>
        /// Gets or Sets InboundSettings
        /// </summary>
        [JsonPropertyName("inboundSettings")]
        public InboundSettings? InboundSettings { get { return this.InboundSettingsOption.Value; } set { this.InboundSettingsOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime? UpdatedAt { get { return this.UpdatedAtOption.Value; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkspaceGetResponseData {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  DefaultInstanceId: ").Append(DefaultInstanceId).Append("\n");
            sb.Append("  DefaultEmailDomainId: ").Append(DefaultEmailDomainId).Append("\n");
            sb.Append("  InboundSettings: ").Append(InboundSettings).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WorkspaceGetResponseData" />
    /// </summary>
    public partial class WorkspaceGetResponseDataJsonConverter : JsonConverter<WorkspaceGetResponseData>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceGetResponseDataJsonConverter" /> class.
        /// </summary>
        public WorkspaceGetResponseDataJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public string UpdatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="WorkspaceGetResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WorkspaceGetResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> name = default;
            Option<string?> slug = default;
            Option<string?> color = default;
            Option<string?> defaultInstanceId = default;
            Option<string?> defaultEmailDomainId = default;
            Option<InboundSettings?> inboundSettings = default;
            Option<DateTime?> updatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "slug":
                            slug = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "color":
                            color = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "defaultInstanceId":
                            defaultInstanceId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "defaultEmailDomainId":
                            defaultEmailDomainId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "inboundSettings":
                            inboundSettings = new Option<InboundSettings?>(JsonSerializer.Deserialize<InboundSettings>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class WorkspaceGetResponseData.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class WorkspaceGetResponseData.");

            if (slug.IsSet && slug.Value == null)
                throw new ArgumentNullException(nameof(slug), "Property is not nullable for class WorkspaceGetResponseData.");

            if (color.IsSet && color.Value == null)
                throw new ArgumentNullException(nameof(color), "Property is not nullable for class WorkspaceGetResponseData.");

            if (defaultInstanceId.IsSet && defaultInstanceId.Value == null)
                throw new ArgumentNullException(nameof(defaultInstanceId), "Property is not nullable for class WorkspaceGetResponseData.");

            if (defaultEmailDomainId.IsSet && defaultEmailDomainId.Value == null)
                throw new ArgumentNullException(nameof(defaultEmailDomainId), "Property is not nullable for class WorkspaceGetResponseData.");

            if (inboundSettings.IsSet && inboundSettings.Value == null)
                throw new ArgumentNullException(nameof(inboundSettings), "Property is not nullable for class WorkspaceGetResponseData.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class WorkspaceGetResponseData.");

            return new WorkspaceGetResponseData(id, name, slug, color, defaultInstanceId, defaultEmailDomainId, inboundSettings, updatedAt);
        }

        /// <summary>
        /// Serializes a <see cref="WorkspaceGetResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workspaceGetResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WorkspaceGetResponseData workspaceGetResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, workspaceGetResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WorkspaceGetResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workspaceGetResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WorkspaceGetResponseData workspaceGetResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (workspaceGetResponseData.IdOption.IsSet && workspaceGetResponseData.Id == null)
                throw new ArgumentNullException(nameof(workspaceGetResponseData.Id), "Property is required for class WorkspaceGetResponseData.");

            if (workspaceGetResponseData.NameOption.IsSet && workspaceGetResponseData.Name == null)
                throw new ArgumentNullException(nameof(workspaceGetResponseData.Name), "Property is required for class WorkspaceGetResponseData.");

            if (workspaceGetResponseData.SlugOption.IsSet && workspaceGetResponseData.Slug == null)
                throw new ArgumentNullException(nameof(workspaceGetResponseData.Slug), "Property is required for class WorkspaceGetResponseData.");

            if (workspaceGetResponseData.ColorOption.IsSet && workspaceGetResponseData.Color == null)
                throw new ArgumentNullException(nameof(workspaceGetResponseData.Color), "Property is required for class WorkspaceGetResponseData.");

            if (workspaceGetResponseData.DefaultInstanceIdOption.IsSet && workspaceGetResponseData.DefaultInstanceId == null)
                throw new ArgumentNullException(nameof(workspaceGetResponseData.DefaultInstanceId), "Property is required for class WorkspaceGetResponseData.");

            if (workspaceGetResponseData.DefaultEmailDomainIdOption.IsSet && workspaceGetResponseData.DefaultEmailDomainId == null)
                throw new ArgumentNullException(nameof(workspaceGetResponseData.DefaultEmailDomainId), "Property is required for class WorkspaceGetResponseData.");

            if (workspaceGetResponseData.InboundSettingsOption.IsSet && workspaceGetResponseData.InboundSettings == null)
                throw new ArgumentNullException(nameof(workspaceGetResponseData.InboundSettings), "Property is required for class WorkspaceGetResponseData.");

            if (workspaceGetResponseData.IdOption.IsSet)
                writer.WriteString("id", workspaceGetResponseData.Id);

            if (workspaceGetResponseData.NameOption.IsSet)
                writer.WriteString("name", workspaceGetResponseData.Name);

            if (workspaceGetResponseData.SlugOption.IsSet)
                writer.WriteString("slug", workspaceGetResponseData.Slug);

            if (workspaceGetResponseData.ColorOption.IsSet)
                writer.WriteString("color", workspaceGetResponseData.Color);

            if (workspaceGetResponseData.DefaultInstanceIdOption.IsSet)
                writer.WriteString("defaultInstanceId", workspaceGetResponseData.DefaultInstanceId);

            if (workspaceGetResponseData.DefaultEmailDomainIdOption.IsSet)
                writer.WriteString("defaultEmailDomainId", workspaceGetResponseData.DefaultEmailDomainId);

            if (workspaceGetResponseData.InboundSettingsOption.IsSet)
            {
                writer.WritePropertyName("inboundSettings");
                JsonSerializer.Serialize(writer, workspaceGetResponseData.InboundSettings, jsonSerializerOptions);
            }
            if (workspaceGetResponseData.UpdatedAtOption.IsSet)
                writer.WriteString("updatedAt", workspaceGetResponseData.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));
        }
    }
}
