/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifique.sdk.ApiClient;
/**
 * NtfAddonsFormConfirmRequest
 */
@JsonPropertyOrder({
  NtfAddonsFormConfirmRequest.JSON_PROPERTY_CONFIRMATION_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfAddonsFormConfirmRequest {
  public static final String JSON_PROPERTY_CONFIRMATION_TOKEN = "confirmationToken";
  @javax.annotation.Nonnull
  private String confirmationToken;

  public NtfAddonsFormConfirmRequest() { 
  }

  public NtfAddonsFormConfirmRequest confirmationToken(@javax.annotation.Nonnull String confirmationToken) {
    this.confirmationToken = confirmationToken;
    return this;
  }

  /**
   * Get confirmationToken
   * @return confirmationToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONFIRMATION_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getConfirmationToken() {
    return confirmationToken;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIRMATION_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfirmationToken(@javax.annotation.Nonnull String confirmationToken) {
    this.confirmationToken = confirmationToken;
  }


  /**
   * Return true if this NtfAddons_FormConfirmRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfAddonsFormConfirmRequest ntfAddonsFormConfirmRequest = (NtfAddonsFormConfirmRequest) o;
    return Objects.equals(this.confirmationToken, ntfAddonsFormConfirmRequest.confirmationToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmationToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfAddonsFormConfirmRequest {\n");
    sb.append("    confirmationToken: ").append(toIndentedString(confirmationToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `confirmationToken` to the URL query string
    if (getConfirmationToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconfirmationToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConfirmationToken()))));
    }

    return joiner.toString();
  }
}

