/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.notifique.sdk.openapi.models.NtfAutoStepSendEmailConfig;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifique.sdk.ApiClient;
/**
 * NtfAutoStepSendEmail
 */
@JsonPropertyOrder({
  NtfAutoStepSendEmail.JSON_PROPERTY_STEP_KEY,
  NtfAutoStepSendEmail.JSON_PROPERTY_STEP_TYPE,
  NtfAutoStepSendEmail.JSON_PROPERTY_CONFIG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfAutoStepSendEmail {
  public static final String JSON_PROPERTY_STEP_KEY = "stepKey";
  @javax.annotation.Nonnull
  private String stepKey;

  /**
   * Gets or Sets stepType
   */
  public enum StepTypeEnum {
    SEND_EMAIL(String.valueOf("sendEmail"));

    private String value;

    StepTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StepTypeEnum fromValue(String value) {
      for (StepTypeEnum b : StepTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STEP_TYPE = "stepType";
  @javax.annotation.Nonnull
  private StepTypeEnum stepType;

  public static final String JSON_PROPERTY_CONFIG = "config";
  @javax.annotation.Nonnull
  private NtfAutoStepSendEmailConfig config;

  public NtfAutoStepSendEmail() { 
  }

  public NtfAutoStepSendEmail stepKey(@javax.annotation.Nonnull String stepKey) {
    this.stepKey = stepKey;
    return this;
  }

  /**
   * Get stepKey
   * @return stepKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STEP_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStepKey() {
    return stepKey;
  }


  @JsonProperty(value = JSON_PROPERTY_STEP_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStepKey(@javax.annotation.Nonnull String stepKey) {
    this.stepKey = stepKey;
  }


  public NtfAutoStepSendEmail stepType(@javax.annotation.Nonnull StepTypeEnum stepType) {
    this.stepType = stepType;
    return this;
  }

  /**
   * Get stepType
   * @return stepType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STEP_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StepTypeEnum getStepType() {
    return stepType;
  }


  @JsonProperty(value = JSON_PROPERTY_STEP_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStepType(@javax.annotation.Nonnull StepTypeEnum stepType) {
    this.stepType = stepType;
  }


  public NtfAutoStepSendEmail config(@javax.annotation.Nonnull NtfAutoStepSendEmailConfig config) {
    this.config = config;
    return this;
  }

  /**
   * Get config
   * @return config
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public NtfAutoStepSendEmailConfig getConfig() {
    return config;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfig(@javax.annotation.Nonnull NtfAutoStepSendEmailConfig config) {
    this.config = config;
  }


  /**
   * Return true if this NtfAuto_StepSendEmail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfAutoStepSendEmail ntfAutoStepSendEmail = (NtfAutoStepSendEmail) o;
    return Objects.equals(this.stepKey, ntfAutoStepSendEmail.stepKey) &&
        Objects.equals(this.stepType, ntfAutoStepSendEmail.stepType) &&
        Objects.equals(this.config, ntfAutoStepSendEmail.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stepKey, stepType, config);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfAutoStepSendEmail {\n");
    sb.append("    stepKey: ").append(toIndentedString(stepKey)).append("\n");
    sb.append("    stepType: ").append(toIndentedString(stepType)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `stepKey` to the URL query string
    if (getStepKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstepKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStepKey()))));
    }

    // add `stepType` to the URL query string
    if (getStepType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstepType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStepType()))));
    }

    // add `config` to the URL query string
    if (getConfig() != null) {
      joiner.add(getConfig().toUrlQueryString(prefix + "config" + suffix));
    }

    return joiner.toString();
  }
}

