/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.notifique.sdk.openapi.models.NtfVoiceCallEvent;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifique.sdk.ApiClient;
/**
 * NtfVoiceDetailEnvelopeData
 */
@JsonPropertyOrder({
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_ID,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_WORKSPACE_ID,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_PHONE_NUMBER_ID,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_DIRECTION,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_FROM_E164,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_TO_E164,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_STATUS,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_CALL_SESSION_ID,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_CALL_LEG_ID,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_ANSWERED_AT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_ENDED_AT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_DURATION_SECS,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_HANGUP_CAUSE,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_RECORDING_AVAILABLE,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_RECORDING_ID,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_DTMF_DIGITS,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_GATHER_RESULT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_MACHINE_DETECTION_RESULT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_SPEAK_TEXT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_PLAY_AUDIO_URL,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_CHARGED_AS,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_CHARGE_AMOUNT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_CLIENT_STATE,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_METADATA,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_CREATED_AT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_UPDATED_AT,
  NtfVoiceDetailEnvelopeData.JSON_PROPERTY_EVENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfVoiceDetailEnvelopeData {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_WORKSPACE_ID = "workspaceId";
  @javax.annotation.Nullable
  private String workspaceId;

  public static final String JSON_PROPERTY_PHONE_NUMBER_ID = "phoneNumberId";
  @javax.annotation.Nullable
  private String phoneNumberId;

  /**
   * Gets or Sets direction
   */
  public enum DirectionEnum {
    OUTBOUND(String.valueOf("OUTBOUND")),
    
    INBOUND(String.valueOf("INBOUND"));

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DirectionEnum fromValue(String value) {
      for (DirectionEnum b : DirectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DIRECTION = "direction";
  @javax.annotation.Nullable
  private DirectionEnum direction;

  public static final String JSON_PROPERTY_FROM_E164 = "fromE164";
  @javax.annotation.Nullable
  private String fromE164;

  public static final String JSON_PROPERTY_TO_E164 = "toE164";
  @javax.annotation.Nullable
  private String toE164;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    QUEUED(String.valueOf("QUEUED")),
    
    INITIATED(String.valueOf("INITIATED")),
    
    RINGING(String.valueOf("RINGING")),
    
    ANSWERED(String.valueOf("ANSWERED")),
    
    COMPLETED(String.valueOf("COMPLETED")),
    
    FAILED(String.valueOf("FAILED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_CALL_SESSION_ID = "callSessionId";
  @javax.annotation.Nullable
  private String callSessionId;

  public static final String JSON_PROPERTY_CALL_LEG_ID = "callLegId";
  @javax.annotation.Nullable
  private String callLegId;

  public static final String JSON_PROPERTY_ANSWERED_AT = "answeredAt";
  @javax.annotation.Nullable
  private OffsetDateTime answeredAt;

  public static final String JSON_PROPERTY_ENDED_AT = "endedAt";
  @javax.annotation.Nullable
  private OffsetDateTime endedAt;

  public static final String JSON_PROPERTY_DURATION_SECS = "durationSecs";
  @javax.annotation.Nullable
  private Integer durationSecs;

  public static final String JSON_PROPERTY_HANGUP_CAUSE = "hangupCause";
  @javax.annotation.Nullable
  private String hangupCause;

  public static final String JSON_PROPERTY_RECORDING_AVAILABLE = "recordingAvailable";
  @javax.annotation.Nullable
  private Boolean recordingAvailable;

  public static final String JSON_PROPERTY_RECORDING_ID = "recordingId";
  @javax.annotation.Nullable
  private String recordingId;

  public static final String JSON_PROPERTY_DTMF_DIGITS = "dtmfDigits";
  @javax.annotation.Nullable
  private String dtmfDigits;

  public static final String JSON_PROPERTY_GATHER_RESULT = "gatherResult";
  @javax.annotation.Nullable
  private String gatherResult;

  public static final String JSON_PROPERTY_MACHINE_DETECTION_RESULT = "machineDetectionResult";
  @javax.annotation.Nullable
  private String machineDetectionResult;

  public static final String JSON_PROPERTY_SPEAK_TEXT = "speakText";
  @javax.annotation.Nullable
  private String speakText;

  public static final String JSON_PROPERTY_PLAY_AUDIO_URL = "playAudioUrl";
  @javax.annotation.Nullable
  private String playAudioUrl;

  public static final String JSON_PROPERTY_CHARGED_AS = "chargedAs";
  @javax.annotation.Nullable
  private String chargedAs;

  public static final String JSON_PROPERTY_CHARGE_AMOUNT = "chargeAmount";
  @javax.annotation.Nullable
  private BigDecimal chargeAmount;

  public static final String JSON_PROPERTY_CLIENT_STATE = "clientState";
  @javax.annotation.Nullable
  private String clientState;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Object metadata;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_EVENTS = "events";
  @javax.annotation.Nullable
  private List<NtfVoiceCallEvent> events = new ArrayList<>();

  public NtfVoiceDetailEnvelopeData() { 
  }

  public NtfVoiceDetailEnvelopeData id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public NtfVoiceDetailEnvelopeData workspaceId(@javax.annotation.Nullable String workspaceId) {
    this.workspaceId = workspaceId;
    return this;
  }

  /**
   * Get workspaceId
   * @return workspaceId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getWorkspaceId() {
    return workspaceId;
  }


  @JsonProperty(value = JSON_PROPERTY_WORKSPACE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkspaceId(@javax.annotation.Nullable String workspaceId) {
    this.workspaceId = workspaceId;
  }


  public NtfVoiceDetailEnvelopeData phoneNumberId(@javax.annotation.Nullable String phoneNumberId) {
    this.phoneNumberId = phoneNumberId;
    return this;
  }

  /**
   * Get phoneNumberId
   * @return phoneNumberId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoneNumberId() {
    return phoneNumberId;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumberId(@javax.annotation.Nullable String phoneNumberId) {
    this.phoneNumberId = phoneNumberId;
  }


  public NtfVoiceDetailEnvelopeData direction(@javax.annotation.Nullable DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   * @return direction
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIRECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DirectionEnum getDirection() {
    return direction;
  }


  @JsonProperty(value = JSON_PROPERTY_DIRECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirection(@javax.annotation.Nullable DirectionEnum direction) {
    this.direction = direction;
  }


  public NtfVoiceDetailEnvelopeData fromE164(@javax.annotation.Nullable String fromE164) {
    this.fromE164 = fromE164;
    return this;
  }

  /**
   * Origem em dígitos E.164, sem &#x60;+&#x60;.
   * @return fromE164
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM_E164, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFromE164() {
    return fromE164;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM_E164, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromE164(@javax.annotation.Nullable String fromE164) {
    this.fromE164 = fromE164;
  }


  public NtfVoiceDetailEnvelopeData toE164(@javax.annotation.Nullable String toE164) {
    this.toE164 = toE164;
    return this;
  }

  /**
   * Destino em dígitos E.164, sem &#x60;+&#x60;.
   * @return toE164
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO_E164, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getToE164() {
    return toE164;
  }


  @JsonProperty(value = JSON_PROPERTY_TO_E164, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToE164(@javax.annotation.Nullable String toE164) {
    this.toE164 = toE164;
  }


  public NtfVoiceDetailEnvelopeData status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public NtfVoiceDetailEnvelopeData callSessionId(@javax.annotation.Nullable String callSessionId) {
    this.callSessionId = callSessionId;
    return this;
  }

  /**
   * Get callSessionId
   * @return callSessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALL_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCallSessionId() {
    return callSessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_CALL_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallSessionId(@javax.annotation.Nullable String callSessionId) {
    this.callSessionId = callSessionId;
  }


  public NtfVoiceDetailEnvelopeData callLegId(@javax.annotation.Nullable String callLegId) {
    this.callLegId = callLegId;
    return this;
  }

  /**
   * Get callLegId
   * @return callLegId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALL_LEG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCallLegId() {
    return callLegId;
  }


  @JsonProperty(value = JSON_PROPERTY_CALL_LEG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallLegId(@javax.annotation.Nullable String callLegId) {
    this.callLegId = callLegId;
  }


  public NtfVoiceDetailEnvelopeData answeredAt(@javax.annotation.Nullable OffsetDateTime answeredAt) {
    this.answeredAt = answeredAt;
    return this;
  }

  /**
   * Get answeredAt
   * @return answeredAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANSWERED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getAnsweredAt() {
    return answeredAt;
  }


  @JsonProperty(value = JSON_PROPERTY_ANSWERED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnsweredAt(@javax.annotation.Nullable OffsetDateTime answeredAt) {
    this.answeredAt = answeredAt;
  }


  public NtfVoiceDetailEnvelopeData endedAt(@javax.annotation.Nullable OffsetDateTime endedAt) {
    this.endedAt = endedAt;
    return this;
  }

  /**
   * Get endedAt
   * @return endedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEndedAt() {
    return endedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndedAt(@javax.annotation.Nullable OffsetDateTime endedAt) {
    this.endedAt = endedAt;
  }


  public NtfVoiceDetailEnvelopeData durationSecs(@javax.annotation.Nullable Integer durationSecs) {
    this.durationSecs = durationSecs;
    return this;
  }

  /**
   * Get durationSecs
   * @return durationSecs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURATION_SECS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getDurationSecs() {
    return durationSecs;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION_SECS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDurationSecs(@javax.annotation.Nullable Integer durationSecs) {
    this.durationSecs = durationSecs;
  }


  public NtfVoiceDetailEnvelopeData hangupCause(@javax.annotation.Nullable String hangupCause) {
    this.hangupCause = hangupCause;
    return this;
  }

  /**
   * Get hangupCause
   * @return hangupCause
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HANGUP_CAUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getHangupCause() {
    return hangupCause;
  }


  @JsonProperty(value = JSON_PROPERTY_HANGUP_CAUSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHangupCause(@javax.annotation.Nullable String hangupCause) {
    this.hangupCause = hangupCause;
  }


  public NtfVoiceDetailEnvelopeData recordingAvailable(@javax.annotation.Nullable Boolean recordingAvailable) {
    this.recordingAvailable = recordingAvailable;
    return this;
  }

  /**
   * Get recordingAvailable
   * @return recordingAvailable
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECORDING_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRecordingAvailable() {
    return recordingAvailable;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDING_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecordingAvailable(@javax.annotation.Nullable Boolean recordingAvailable) {
    this.recordingAvailable = recordingAvailable;
  }


  public NtfVoiceDetailEnvelopeData recordingId(@javax.annotation.Nullable String recordingId) {
    this.recordingId = recordingId;
    return this;
  }

  /**
   * Get recordingId
   * @return recordingId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECORDING_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRecordingId() {
    return recordingId;
  }


  @JsonProperty(value = JSON_PROPERTY_RECORDING_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecordingId(@javax.annotation.Nullable String recordingId) {
    this.recordingId = recordingId;
  }


  public NtfVoiceDetailEnvelopeData dtmfDigits(@javax.annotation.Nullable String dtmfDigits) {
    this.dtmfDigits = dtmfDigits;
    return this;
  }

  /**
   * Get dtmfDigits
   * @return dtmfDigits
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DTMF_DIGITS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDtmfDigits() {
    return dtmfDigits;
  }


  @JsonProperty(value = JSON_PROPERTY_DTMF_DIGITS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDtmfDigits(@javax.annotation.Nullable String dtmfDigits) {
    this.dtmfDigits = dtmfDigits;
  }


  public NtfVoiceDetailEnvelopeData gatherResult(@javax.annotation.Nullable String gatherResult) {
    this.gatherResult = gatherResult;
    return this;
  }

  /**
   * Get gatherResult
   * @return gatherResult
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GATHER_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getGatherResult() {
    return gatherResult;
  }


  @JsonProperty(value = JSON_PROPERTY_GATHER_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGatherResult(@javax.annotation.Nullable String gatherResult) {
    this.gatherResult = gatherResult;
  }


  public NtfVoiceDetailEnvelopeData machineDetectionResult(@javax.annotation.Nullable String machineDetectionResult) {
    this.machineDetectionResult = machineDetectionResult;
    return this;
  }

  /**
   * Get machineDetectionResult
   * @return machineDetectionResult
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MACHINE_DETECTION_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMachineDetectionResult() {
    return machineDetectionResult;
  }


  @JsonProperty(value = JSON_PROPERTY_MACHINE_DETECTION_RESULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMachineDetectionResult(@javax.annotation.Nullable String machineDetectionResult) {
    this.machineDetectionResult = machineDetectionResult;
  }


  public NtfVoiceDetailEnvelopeData speakText(@javax.annotation.Nullable String speakText) {
    this.speakText = speakText;
    return this;
  }

  /**
   * Get speakText
   * @return speakText
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SPEAK_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSpeakText() {
    return speakText;
  }


  @JsonProperty(value = JSON_PROPERTY_SPEAK_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpeakText(@javax.annotation.Nullable String speakText) {
    this.speakText = speakText;
  }


  public NtfVoiceDetailEnvelopeData playAudioUrl(@javax.annotation.Nullable String playAudioUrl) {
    this.playAudioUrl = playAudioUrl;
    return this;
  }

  /**
   * Get playAudioUrl
   * @return playAudioUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLAY_AUDIO_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPlayAudioUrl() {
    return playAudioUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_PLAY_AUDIO_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlayAudioUrl(@javax.annotation.Nullable String playAudioUrl) {
    this.playAudioUrl = playAudioUrl;
  }


  public NtfVoiceDetailEnvelopeData chargedAs(@javax.annotation.Nullable String chargedAs) {
    this.chargedAs = chargedAs;
    return this;
  }

  /**
   * Get chargedAs
   * @return chargedAs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHARGED_AS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChargedAs() {
    return chargedAs;
  }


  @JsonProperty(value = JSON_PROPERTY_CHARGED_AS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargedAs(@javax.annotation.Nullable String chargedAs) {
    this.chargedAs = chargedAs;
  }


  public NtfVoiceDetailEnvelopeData chargeAmount(@javax.annotation.Nullable BigDecimal chargeAmount) {
    this.chargeAmount = chargeAmount;
    return this;
  }

  /**
   * Get chargeAmount
   * @return chargeAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHARGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getChargeAmount() {
    return chargeAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_CHARGE_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargeAmount(@javax.annotation.Nullable BigDecimal chargeAmount) {
    this.chargeAmount = chargeAmount;
  }


  public NtfVoiceDetailEnvelopeData clientState(@javax.annotation.Nullable String clientState) {
    this.clientState = clientState;
    return this;
  }

  /**
   * Get clientState
   * @return clientState
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getClientState() {
    return clientState;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientState(@javax.annotation.Nullable String clientState) {
    this.clientState = clientState;
  }


  public NtfVoiceDetailEnvelopeData metadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }


  public NtfVoiceDetailEnvelopeData createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public NtfVoiceDetailEnvelopeData updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public NtfVoiceDetailEnvelopeData events(@javax.annotation.Nullable List<NtfVoiceCallEvent> events) {
    this.events = events;
    return this;
  }

  public NtfVoiceDetailEnvelopeData addEventsItem(NtfVoiceCallEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Get events
   * @return events
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<NtfVoiceCallEvent> getEvents() {
    return events;
  }


  @JsonProperty(value = JSON_PROPERTY_EVENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvents(@javax.annotation.Nullable List<NtfVoiceCallEvent> events) {
    this.events = events;
  }


  /**
   * Return true if this NtfVoice_DetailEnvelope_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfVoiceDetailEnvelopeData ntfVoiceDetailEnvelopeData = (NtfVoiceDetailEnvelopeData) o;
    return Objects.equals(this.id, ntfVoiceDetailEnvelopeData.id) &&
        Objects.equals(this.workspaceId, ntfVoiceDetailEnvelopeData.workspaceId) &&
        Objects.equals(this.phoneNumberId, ntfVoiceDetailEnvelopeData.phoneNumberId) &&
        Objects.equals(this.direction, ntfVoiceDetailEnvelopeData.direction) &&
        Objects.equals(this.fromE164, ntfVoiceDetailEnvelopeData.fromE164) &&
        Objects.equals(this.toE164, ntfVoiceDetailEnvelopeData.toE164) &&
        Objects.equals(this.status, ntfVoiceDetailEnvelopeData.status) &&
        Objects.equals(this.callSessionId, ntfVoiceDetailEnvelopeData.callSessionId) &&
        Objects.equals(this.callLegId, ntfVoiceDetailEnvelopeData.callLegId) &&
        Objects.equals(this.answeredAt, ntfVoiceDetailEnvelopeData.answeredAt) &&
        Objects.equals(this.endedAt, ntfVoiceDetailEnvelopeData.endedAt) &&
        Objects.equals(this.durationSecs, ntfVoiceDetailEnvelopeData.durationSecs) &&
        Objects.equals(this.hangupCause, ntfVoiceDetailEnvelopeData.hangupCause) &&
        Objects.equals(this.recordingAvailable, ntfVoiceDetailEnvelopeData.recordingAvailable) &&
        Objects.equals(this.recordingId, ntfVoiceDetailEnvelopeData.recordingId) &&
        Objects.equals(this.dtmfDigits, ntfVoiceDetailEnvelopeData.dtmfDigits) &&
        Objects.equals(this.gatherResult, ntfVoiceDetailEnvelopeData.gatherResult) &&
        Objects.equals(this.machineDetectionResult, ntfVoiceDetailEnvelopeData.machineDetectionResult) &&
        Objects.equals(this.speakText, ntfVoiceDetailEnvelopeData.speakText) &&
        Objects.equals(this.playAudioUrl, ntfVoiceDetailEnvelopeData.playAudioUrl) &&
        Objects.equals(this.chargedAs, ntfVoiceDetailEnvelopeData.chargedAs) &&
        Objects.equals(this.chargeAmount, ntfVoiceDetailEnvelopeData.chargeAmount) &&
        Objects.equals(this.clientState, ntfVoiceDetailEnvelopeData.clientState) &&
        Objects.equals(this.metadata, ntfVoiceDetailEnvelopeData.metadata) &&
        Objects.equals(this.createdAt, ntfVoiceDetailEnvelopeData.createdAt) &&
        Objects.equals(this.updatedAt, ntfVoiceDetailEnvelopeData.updatedAt) &&
        Objects.equals(this.events, ntfVoiceDetailEnvelopeData.events);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, workspaceId, phoneNumberId, direction, fromE164, toE164, status, callSessionId, callLegId, answeredAt, endedAt, durationSecs, hangupCause, recordingAvailable, recordingId, dtmfDigits, gatherResult, machineDetectionResult, speakText, playAudioUrl, chargedAs, chargeAmount, clientState, metadata, createdAt, updatedAt, events);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfVoiceDetailEnvelopeData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("    phoneNumberId: ").append(toIndentedString(phoneNumberId)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    fromE164: ").append(toIndentedString(fromE164)).append("\n");
    sb.append("    toE164: ").append(toIndentedString(toE164)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    callSessionId: ").append(toIndentedString(callSessionId)).append("\n");
    sb.append("    callLegId: ").append(toIndentedString(callLegId)).append("\n");
    sb.append("    answeredAt: ").append(toIndentedString(answeredAt)).append("\n");
    sb.append("    endedAt: ").append(toIndentedString(endedAt)).append("\n");
    sb.append("    durationSecs: ").append(toIndentedString(durationSecs)).append("\n");
    sb.append("    hangupCause: ").append(toIndentedString(hangupCause)).append("\n");
    sb.append("    recordingAvailable: ").append(toIndentedString(recordingAvailable)).append("\n");
    sb.append("    recordingId: ").append(toIndentedString(recordingId)).append("\n");
    sb.append("    dtmfDigits: ").append(toIndentedString(dtmfDigits)).append("\n");
    sb.append("    gatherResult: ").append(toIndentedString(gatherResult)).append("\n");
    sb.append("    machineDetectionResult: ").append(toIndentedString(machineDetectionResult)).append("\n");
    sb.append("    speakText: ").append(toIndentedString(speakText)).append("\n");
    sb.append("    playAudioUrl: ").append(toIndentedString(playAudioUrl)).append("\n");
    sb.append("    chargedAs: ").append(toIndentedString(chargedAs)).append("\n");
    sb.append("    chargeAmount: ").append(toIndentedString(chargeAmount)).append("\n");
    sb.append("    clientState: ").append(toIndentedString(clientState)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `workspaceId` to the URL query string
    if (getWorkspaceId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sworkspaceId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWorkspaceId()))));
    }

    // add `phoneNumberId` to the URL query string
    if (getPhoneNumberId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphoneNumberId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhoneNumberId()))));
    }

    // add `direction` to the URL query string
    if (getDirection() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdirection%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDirection()))));
    }

    // add `fromE164` to the URL query string
    if (getFromE164() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfromE164%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFromE164()))));
    }

    // add `toE164` to the URL query string
    if (getToE164() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stoE164%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToE164()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `callSessionId` to the URL query string
    if (getCallSessionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scallSessionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallSessionId()))));
    }

    // add `callLegId` to the URL query string
    if (getCallLegId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scallLegId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallLegId()))));
    }

    // add `answeredAt` to the URL query string
    if (getAnsweredAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sansweredAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAnsweredAt()))));
    }

    // add `endedAt` to the URL query string
    if (getEndedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sendedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEndedAt()))));
    }

    // add `durationSecs` to the URL query string
    if (getDurationSecs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdurationSecs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDurationSecs()))));
    }

    // add `hangupCause` to the URL query string
    if (getHangupCause() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shangupCause%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHangupCause()))));
    }

    // add `recordingAvailable` to the URL query string
    if (getRecordingAvailable() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srecordingAvailable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRecordingAvailable()))));
    }

    // add `recordingId` to the URL query string
    if (getRecordingId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srecordingId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRecordingId()))));
    }

    // add `dtmfDigits` to the URL query string
    if (getDtmfDigits() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdtmfDigits%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDtmfDigits()))));
    }

    // add `gatherResult` to the URL query string
    if (getGatherResult() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sgatherResult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGatherResult()))));
    }

    // add `machineDetectionResult` to the URL query string
    if (getMachineDetectionResult() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smachineDetectionResult%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMachineDetectionResult()))));
    }

    // add `speakText` to the URL query string
    if (getSpeakText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sspeakText%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSpeakText()))));
    }

    // add `playAudioUrl` to the URL query string
    if (getPlayAudioUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%splayAudioUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlayAudioUrl()))));
    }

    // add `chargedAs` to the URL query string
    if (getChargedAs() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schargedAs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChargedAs()))));
    }

    // add `chargeAmount` to the URL query string
    if (getChargeAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schargeAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChargeAmount()))));
    }

    // add `clientState` to the URL query string
    if (getClientState() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sclientState%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClientState()))));
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetadata%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetadata()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `events` to the URL query string
    if (getEvents() != null) {
      for (int i = 0; i < getEvents().size(); i++) {
        if (getEvents().get(i) != null) {
          joiner.add(getEvents().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sevents%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

