/*
 * Notifique API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.notifique.sdk.openapi.models;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.notifique.sdk.ApiClient;
/**
 * Arquivo de mídia do inbound em base64.
 */
@JsonPropertyOrder({
  NtfWaWhatsAppInboundMediaResponse.JSON_PROPERTY_CONTENT_TYPE,
  NtfWaWhatsAppInboundMediaResponse.JSON_PROPERTY_FILE_NAME,
  NtfWaWhatsAppInboundMediaResponse.JSON_PROPERTY_BASE64
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0-SNAPSHOT")
public class NtfWaWhatsAppInboundMediaResponse {
  public static final String JSON_PROPERTY_CONTENT_TYPE = "contentType";
  @javax.annotation.Nonnull
  private String contentType;

  public static final String JSON_PROPERTY_FILE_NAME = "fileName";
  @javax.annotation.Nullable
  private String fileName;

  public static final String JSON_PROPERTY_BASE64 = "base64";
  @javax.annotation.Nonnull
  private String base64;

  public NtfWaWhatsAppInboundMediaResponse() { 
  }

  public NtfWaWhatsAppInboundMediaResponse contentType(@javax.annotation.Nonnull String contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * Get contentType
   * @return contentType
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getContentType() {
    return contentType;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContentType(@javax.annotation.Nonnull String contentType) {
    this.contentType = contentType;
  }


  public NtfWaWhatsAppInboundMediaResponse fileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
    return this;
  }

  /**
   * Get fileName
   * @return fileName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFileName() {
    return fileName;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
  }


  public NtfWaWhatsAppInboundMediaResponse base64(@javax.annotation.Nonnull String base64) {
    this.base64 = base64;
    return this;
  }

  /**
   * Conteúdo do arquivo codificado em base64 (sem prefixo data:).
   * @return base64
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BASE64, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBase64() {
    return base64;
  }


  @JsonProperty(value = JSON_PROPERTY_BASE64, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBase64(@javax.annotation.Nonnull String base64) {
    this.base64 = base64;
  }


  /**
   * Return true if this NtfWa_WhatsAppInboundMediaResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NtfWaWhatsAppInboundMediaResponse ntfWaWhatsAppInboundMediaResponse = (NtfWaWhatsAppInboundMediaResponse) o;
    return Objects.equals(this.contentType, ntfWaWhatsAppInboundMediaResponse.contentType) &&
        Objects.equals(this.fileName, ntfWaWhatsAppInboundMediaResponse.fileName) &&
        Objects.equals(this.base64, ntfWaWhatsAppInboundMediaResponse.base64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentType, fileName, base64);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NtfWaWhatsAppInboundMediaResponse {\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    base64: ").append(toIndentedString(base64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `contentType` to the URL query string
    if (getContentType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontentType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentType()))));
    }

    // add `fileName` to the URL query string
    if (getFileName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfileName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFileName()))));
    }

    // add `base64` to the URL query string
    if (getBase64() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbase64%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBase64()))));
    }

    return joiner.toString();
  }
}

