/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfWhCreateWebhookResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfWhCreateWebhookResponseData{}

// NtfWhCreateWebhookResponseData struct for NtfWhCreateWebhookResponseData
type NtfWhCreateWebhookResponseData struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
	Events []string `json:"events,omitempty"`
	InstanceIds []map[string]interface{} `json:"instanceIds,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	Secret *string `json:"secret,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}

// NewNtfWhCreateWebhookResponseData instantiates a new NtfWhCreateWebhookResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfWhCreateWebhookResponseData() *NtfWhCreateWebhookResponseData {
	this := NtfWhCreateWebhookResponseData{}
	return &this
}

// NewNtfWhCreateWebhookResponseDataWithDefaults instantiates a new NtfWhCreateWebhookResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfWhCreateWebhookResponseDataWithDefaults() *NtfWhCreateWebhookResponseData {
	this := NtfWhCreateWebhookResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NtfWhCreateWebhookResponseData) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NtfWhCreateWebhookResponseData) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *NtfWhCreateWebhookResponseData) SetUrl(v string) {
	o.Url = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetEvents() []string {
	if o == nil || IsNil(o.Events) {
		var ret []string
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []string and assigns it to the Events field.
func (o *NtfWhCreateWebhookResponseData) SetEvents(v []string) {
	o.Events = v
}

// GetInstanceIds returns the InstanceIds field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetInstanceIds() []map[string]interface{} {
	if o == nil || IsNil(o.InstanceIds) {
		var ret []map[string]interface{}
		return ret
	}
	return o.InstanceIds
}

// GetInstanceIdsOk returns a tuple with the InstanceIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetInstanceIdsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.InstanceIds) {
		return nil, false
	}
	return o.InstanceIds, true
}

// HasInstanceIds returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasInstanceIds() bool {
	if o != nil && !IsNil(o.InstanceIds) {
		return true
	}

	return false
}

// SetInstanceIds gets a reference to the given []map[string]interface{} and assigns it to the InstanceIds field.
func (o *NtfWhCreateWebhookResponseData) SetInstanceIds(v []map[string]interface{}) {
	o.InstanceIds = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *NtfWhCreateWebhookResponseData) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *NtfWhCreateWebhookResponseData) SetSecret(v string) {
	o.Secret = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *NtfWhCreateWebhookResponseData) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWhCreateWebhookResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *NtfWhCreateWebhookResponseData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *NtfWhCreateWebhookResponseData) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o NtfWhCreateWebhookResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfWhCreateWebhookResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.InstanceIds) {
		toSerialize["instanceIds"] = o.InstanceIds
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableNtfWhCreateWebhookResponseData struct {
	value *NtfWhCreateWebhookResponseData
	isSet bool
}

func (v NullableNtfWhCreateWebhookResponseData) Get() *NtfWhCreateWebhookResponseData {
	return v.value
}

func (v *NullableNtfWhCreateWebhookResponseData) Set(val *NtfWhCreateWebhookResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfWhCreateWebhookResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfWhCreateWebhookResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfWhCreateWebhookResponseData(val *NtfWhCreateWebhookResponseData) *NullableNtfWhCreateWebhookResponseData {
	return &NullableNtfWhCreateWebhookResponseData{value: val, isSet: true}
}

func (v NullableNtfWhCreateWebhookResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfWhCreateWebhookResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


