/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
	"time"
)

// checks if the NtfTgInboundRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfTgInboundRow{}

// NtfTgInboundRow struct for NtfTgInboundRow
type NtfTgInboundRow struct {
	Id *string `json:"id,omitempty"`
	InstanceId *string `json:"instanceId,omitempty"`
	ReceivedAt *time.Time `json:"receivedAt,omitempty"`
	Message *string `json:"message,omitempty"`
	// Rótulo do remetente (@username, nome ou chat).
	FromLabel *string `json:"fromLabel,omitempty"`
}

// NewNtfTgInboundRow instantiates a new NtfTgInboundRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfTgInboundRow() *NtfTgInboundRow {
	this := NtfTgInboundRow{}
	return &this
}

// NewNtfTgInboundRowWithDefaults instantiates a new NtfTgInboundRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfTgInboundRowWithDefaults() *NtfTgInboundRow {
	this := NtfTgInboundRow{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NtfTgInboundRow) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgInboundRow) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NtfTgInboundRow) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NtfTgInboundRow) SetId(v string) {
	o.Id = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *NtfTgInboundRow) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgInboundRow) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *NtfTgInboundRow) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *NtfTgInboundRow) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetReceivedAt returns the ReceivedAt field value if set, zero value otherwise.
func (o *NtfTgInboundRow) GetReceivedAt() time.Time {
	if o == nil || IsNil(o.ReceivedAt) {
		var ret time.Time
		return ret
	}
	return *o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgInboundRow) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ReceivedAt) {
		return nil, false
	}
	return o.ReceivedAt, true
}

// HasReceivedAt returns a boolean if a field has been set.
func (o *NtfTgInboundRow) HasReceivedAt() bool {
	if o != nil && !IsNil(o.ReceivedAt) {
		return true
	}

	return false
}

// SetReceivedAt gets a reference to the given time.Time and assigns it to the ReceivedAt field.
func (o *NtfTgInboundRow) SetReceivedAt(v time.Time) {
	o.ReceivedAt = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NtfTgInboundRow) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgInboundRow) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NtfTgInboundRow) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NtfTgInboundRow) SetMessage(v string) {
	o.Message = &v
}

// GetFromLabel returns the FromLabel field value if set, zero value otherwise.
func (o *NtfTgInboundRow) GetFromLabel() string {
	if o == nil || IsNil(o.FromLabel) {
		var ret string
		return ret
	}
	return *o.FromLabel
}

// GetFromLabelOk returns a tuple with the FromLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgInboundRow) GetFromLabelOk() (*string, bool) {
	if o == nil || IsNil(o.FromLabel) {
		return nil, false
	}
	return o.FromLabel, true
}

// HasFromLabel returns a boolean if a field has been set.
func (o *NtfTgInboundRow) HasFromLabel() bool {
	if o != nil && !IsNil(o.FromLabel) {
		return true
	}

	return false
}

// SetFromLabel gets a reference to the given string and assigns it to the FromLabel field.
func (o *NtfTgInboundRow) SetFromLabel(v string) {
	o.FromLabel = &v
}

func (o NtfTgInboundRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfTgInboundRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if !IsNil(o.ReceivedAt) {
		toSerialize["receivedAt"] = o.ReceivedAt
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.FromLabel) {
		toSerialize["fromLabel"] = o.FromLabel
	}
	return toSerialize, nil
}

type NullableNtfTgInboundRow struct {
	value *NtfTgInboundRow
	isSet bool
}

func (v NullableNtfTgInboundRow) Get() *NtfTgInboundRow {
	return v.value
}

func (v *NullableNtfTgInboundRow) Set(val *NtfTgInboundRow) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfTgInboundRow) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfTgInboundRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfTgInboundRow(val *NtfTgInboundRow) *NullableNtfTgInboundRow {
	return &NullableNtfTgInboundRow{value: val, isSet: true}
}

func (v NullableNtfTgInboundRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfTgInboundRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


