/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NtfTgConnectPageEnableResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfTgConnectPageEnableResponseData{}

// NtfTgConnectPageEnableResponseData struct for NtfTgConnectPageEnableResponseData
type NtfTgConnectPageEnableResponseData struct {
	// URL hospedada da página de conexão (inclui o token).
	HostedUrl string `json:"hostedUrl"`
	// URL para embed em iframe (inclui o token).
	EmbedUrl string `json:"embedUrl"`
	// ID público da página de conexão.
	PublicId string `json:"publicId"`
	// Secret bruto (retornado em enable/rotate). Prefira usar hostedUrl, que já embute o token.
	Secret *string `json:"secret,omitempty"`
	// Snippet HTML de iframe pronto para colar.
	IframeSnippet *string `json:"iframeSnippet,omitempty"`
	ShareableLink *NtfTgShareableLink `json:"shareableLink,omitempty"`
}

type _NtfTgConnectPageEnableResponseData NtfTgConnectPageEnableResponseData

// NewNtfTgConnectPageEnableResponseData instantiates a new NtfTgConnectPageEnableResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfTgConnectPageEnableResponseData(hostedUrl string, embedUrl string, publicId string) *NtfTgConnectPageEnableResponseData {
	this := NtfTgConnectPageEnableResponseData{}
	this.HostedUrl = hostedUrl
	this.EmbedUrl = embedUrl
	this.PublicId = publicId
	return &this
}

// NewNtfTgConnectPageEnableResponseDataWithDefaults instantiates a new NtfTgConnectPageEnableResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfTgConnectPageEnableResponseDataWithDefaults() *NtfTgConnectPageEnableResponseData {
	this := NtfTgConnectPageEnableResponseData{}
	return &this
}

// GetHostedUrl returns the HostedUrl field value
func (o *NtfTgConnectPageEnableResponseData) GetHostedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostedUrl
}

// GetHostedUrlOk returns a tuple with the HostedUrl field value
// and a boolean to check if the value has been set.
func (o *NtfTgConnectPageEnableResponseData) GetHostedUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostedUrl, true
}

// SetHostedUrl sets field value
func (o *NtfTgConnectPageEnableResponseData) SetHostedUrl(v string) {
	o.HostedUrl = v
}

// GetEmbedUrl returns the EmbedUrl field value
func (o *NtfTgConnectPageEnableResponseData) GetEmbedUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmbedUrl
}

// GetEmbedUrlOk returns a tuple with the EmbedUrl field value
// and a boolean to check if the value has been set.
func (o *NtfTgConnectPageEnableResponseData) GetEmbedUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmbedUrl, true
}

// SetEmbedUrl sets field value
func (o *NtfTgConnectPageEnableResponseData) SetEmbedUrl(v string) {
	o.EmbedUrl = v
}

// GetPublicId returns the PublicId field value
func (o *NtfTgConnectPageEnableResponseData) GetPublicId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value
// and a boolean to check if the value has been set.
func (o *NtfTgConnectPageEnableResponseData) GetPublicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicId, true
}

// SetPublicId sets field value
func (o *NtfTgConnectPageEnableResponseData) SetPublicId(v string) {
	o.PublicId = v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *NtfTgConnectPageEnableResponseData) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgConnectPageEnableResponseData) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *NtfTgConnectPageEnableResponseData) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *NtfTgConnectPageEnableResponseData) SetSecret(v string) {
	o.Secret = &v
}

// GetIframeSnippet returns the IframeSnippet field value if set, zero value otherwise.
func (o *NtfTgConnectPageEnableResponseData) GetIframeSnippet() string {
	if o == nil || IsNil(o.IframeSnippet) {
		var ret string
		return ret
	}
	return *o.IframeSnippet
}

// GetIframeSnippetOk returns a tuple with the IframeSnippet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgConnectPageEnableResponseData) GetIframeSnippetOk() (*string, bool) {
	if o == nil || IsNil(o.IframeSnippet) {
		return nil, false
	}
	return o.IframeSnippet, true
}

// HasIframeSnippet returns a boolean if a field has been set.
func (o *NtfTgConnectPageEnableResponseData) HasIframeSnippet() bool {
	if o != nil && !IsNil(o.IframeSnippet) {
		return true
	}

	return false
}

// SetIframeSnippet gets a reference to the given string and assigns it to the IframeSnippet field.
func (o *NtfTgConnectPageEnableResponseData) SetIframeSnippet(v string) {
	o.IframeSnippet = &v
}

// GetShareableLink returns the ShareableLink field value if set, zero value otherwise.
func (o *NtfTgConnectPageEnableResponseData) GetShareableLink() NtfTgShareableLink {
	if o == nil || IsNil(o.ShareableLink) {
		var ret NtfTgShareableLink
		return ret
	}
	return *o.ShareableLink
}

// GetShareableLinkOk returns a tuple with the ShareableLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfTgConnectPageEnableResponseData) GetShareableLinkOk() (*NtfTgShareableLink, bool) {
	if o == nil || IsNil(o.ShareableLink) {
		return nil, false
	}
	return o.ShareableLink, true
}

// HasShareableLink returns a boolean if a field has been set.
func (o *NtfTgConnectPageEnableResponseData) HasShareableLink() bool {
	if o != nil && !IsNil(o.ShareableLink) {
		return true
	}

	return false
}

// SetShareableLink gets a reference to the given NtfTgShareableLink and assigns it to the ShareableLink field.
func (o *NtfTgConnectPageEnableResponseData) SetShareableLink(v NtfTgShareableLink) {
	o.ShareableLink = &v
}

func (o NtfTgConnectPageEnableResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfTgConnectPageEnableResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hostedUrl"] = o.HostedUrl
	toSerialize["embedUrl"] = o.EmbedUrl
	toSerialize["publicId"] = o.PublicId
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.IframeSnippet) {
		toSerialize["iframeSnippet"] = o.IframeSnippet
	}
	if !IsNil(o.ShareableLink) {
		toSerialize["shareableLink"] = o.ShareableLink
	}
	return toSerialize, nil
}

func (o *NtfTgConnectPageEnableResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hostedUrl",
		"embedUrl",
		"publicId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNtfTgConnectPageEnableResponseData := _NtfTgConnectPageEnableResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNtfTgConnectPageEnableResponseData)

	if err != nil {
		return err
	}

	*o = NtfTgConnectPageEnableResponseData(varNtfTgConnectPageEnableResponseData)

	return err
}

type NullableNtfTgConnectPageEnableResponseData struct {
	value *NtfTgConnectPageEnableResponseData
	isSet bool
}

func (v NullableNtfTgConnectPageEnableResponseData) Get() *NtfTgConnectPageEnableResponseData {
	return v.value
}

func (v *NullableNtfTgConnectPageEnableResponseData) Set(val *NtfTgConnectPageEnableResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfTgConnectPageEnableResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfTgConnectPageEnableResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfTgConnectPageEnableResponseData(val *NtfTgConnectPageEnableResponseData) *NullableNtfTgConnectPageEnableResponseData {
	return &NullableNtfTgConnectPageEnableResponseData{value: val, isSet: true}
}

func (v NullableNtfTgConnectPageEnableResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfTgConnectPageEnableResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


