/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfPlatformDeletePaymentMethodResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfPlatformDeletePaymentMethodResponseData{}

// NtfPlatformDeletePaymentMethodResponseData struct for NtfPlatformDeletePaymentMethodResponseData
type NtfPlatformDeletePaymentMethodResponseData struct {
	Id *string `json:"id,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
}

// NewNtfPlatformDeletePaymentMethodResponseData instantiates a new NtfPlatformDeletePaymentMethodResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfPlatformDeletePaymentMethodResponseData() *NtfPlatformDeletePaymentMethodResponseData {
	this := NtfPlatformDeletePaymentMethodResponseData{}
	return &this
}

// NewNtfPlatformDeletePaymentMethodResponseDataWithDefaults instantiates a new NtfPlatformDeletePaymentMethodResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfPlatformDeletePaymentMethodResponseDataWithDefaults() *NtfPlatformDeletePaymentMethodResponseData {
	this := NtfPlatformDeletePaymentMethodResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NtfPlatformDeletePaymentMethodResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfPlatformDeletePaymentMethodResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NtfPlatformDeletePaymentMethodResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NtfPlatformDeletePaymentMethodResponseData) SetId(v string) {
	o.Id = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *NtfPlatformDeletePaymentMethodResponseData) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfPlatformDeletePaymentMethodResponseData) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *NtfPlatformDeletePaymentMethodResponseData) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *NtfPlatformDeletePaymentMethodResponseData) SetDeleted(v bool) {
	o.Deleted = &v
}

func (o NtfPlatformDeletePaymentMethodResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfPlatformDeletePaymentMethodResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableNtfPlatformDeletePaymentMethodResponseData struct {
	value *NtfPlatformDeletePaymentMethodResponseData
	isSet bool
}

func (v NullableNtfPlatformDeletePaymentMethodResponseData) Get() *NtfPlatformDeletePaymentMethodResponseData {
	return v.value
}

func (v *NullableNtfPlatformDeletePaymentMethodResponseData) Set(val *NtfPlatformDeletePaymentMethodResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfPlatformDeletePaymentMethodResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfPlatformDeletePaymentMethodResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfPlatformDeletePaymentMethodResponseData(val *NtfPlatformDeletePaymentMethodResponseData) *NullableNtfPlatformDeletePaymentMethodResponseData {
	return &NullableNtfPlatformDeletePaymentMethodResponseData{value: val, isSet: true}
}

func (v NullableNtfPlatformDeletePaymentMethodResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfPlatformDeletePaymentMethodResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


