/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NtfAutoErrorGraphValidation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfAutoErrorGraphValidation{}

// NtfAutoErrorGraphValidation struct for NtfAutoErrorGraphValidation
type NtfAutoErrorGraphValidation struct {
	Success bool `json:"success"`
	// Mensagem detalhada (validação Zod concatena com `; ` em INVALID_GRAPH).
	Error string `json:"error"`
	// Código estável quando o grafo ou vínculo com evento falha.
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

type _NtfAutoErrorGraphValidation NtfAutoErrorGraphValidation

// NewNtfAutoErrorGraphValidation instantiates a new NtfAutoErrorGraphValidation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfAutoErrorGraphValidation(success bool, error_ string) *NtfAutoErrorGraphValidation {
	this := NtfAutoErrorGraphValidation{}
	this.Success = success
	this.Error = error_
	return &this
}

// NewNtfAutoErrorGraphValidationWithDefaults instantiates a new NtfAutoErrorGraphValidation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfAutoErrorGraphValidationWithDefaults() *NtfAutoErrorGraphValidation {
	this := NtfAutoErrorGraphValidation{}
	return &this
}

// GetSuccess returns the Success field value
func (o *NtfAutoErrorGraphValidation) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *NtfAutoErrorGraphValidation) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *NtfAutoErrorGraphValidation) SetSuccess(v bool) {
	o.Success = v
}

// GetError returns the Error field value
func (o *NtfAutoErrorGraphValidation) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *NtfAutoErrorGraphValidation) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *NtfAutoErrorGraphValidation) SetError(v string) {
	o.Error = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *NtfAutoErrorGraphValidation) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfAutoErrorGraphValidation) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *NtfAutoErrorGraphValidation) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *NtfAutoErrorGraphValidation) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NtfAutoErrorGraphValidation) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfAutoErrorGraphValidation) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NtfAutoErrorGraphValidation) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NtfAutoErrorGraphValidation) SetMessage(v string) {
	o.Message = &v
}

func (o NtfAutoErrorGraphValidation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfAutoErrorGraphValidation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["error"] = o.Error
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *NtfAutoErrorGraphValidation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNtfAutoErrorGraphValidation := _NtfAutoErrorGraphValidation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNtfAutoErrorGraphValidation)

	if err != nil {
		return err
	}

	*o = NtfAutoErrorGraphValidation(varNtfAutoErrorGraphValidation)

	return err
}

type NullableNtfAutoErrorGraphValidation struct {
	value *NtfAutoErrorGraphValidation
	isSet bool
}

func (v NullableNtfAutoErrorGraphValidation) Get() *NtfAutoErrorGraphValidation {
	return v.value
}

func (v *NullableNtfAutoErrorGraphValidation) Set(val *NtfAutoErrorGraphValidation) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfAutoErrorGraphValidation) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfAutoErrorGraphValidation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfAutoErrorGraphValidation(val *NtfAutoErrorGraphValidation) *NullableNtfAutoErrorGraphValidation {
	return &NullableNtfAutoErrorGraphValidation{value: val, isSet: true}
}

func (v NullableNtfAutoErrorGraphValidation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfAutoErrorGraphValidation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


