/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// NtfAddonsWaitlistSubscribeData - struct for NtfAddonsWaitlistSubscribeData
type NtfAddonsWaitlistSubscribeData struct {
	NtfAddonsWaitlistSubscribeDataOneOf *NtfAddonsWaitlistSubscribeDataOneOf
	NtfAddonsWaitlistSubscribeDataOneOf1 *NtfAddonsWaitlistSubscribeDataOneOf1
}

// NtfAddonsWaitlistSubscribeDataOneOfAsNtfAddonsWaitlistSubscribeData is a convenience function that returns NtfAddonsWaitlistSubscribeDataOneOf wrapped in NtfAddonsWaitlistSubscribeData
func NtfAddonsWaitlistSubscribeDataOneOfAsNtfAddonsWaitlistSubscribeData(v *NtfAddonsWaitlistSubscribeDataOneOf) NtfAddonsWaitlistSubscribeData {
	return NtfAddonsWaitlistSubscribeData{
		NtfAddonsWaitlistSubscribeDataOneOf: v,
	}
}

// NtfAddonsWaitlistSubscribeDataOneOf1AsNtfAddonsWaitlistSubscribeData is a convenience function that returns NtfAddonsWaitlistSubscribeDataOneOf1 wrapped in NtfAddonsWaitlistSubscribeData
func NtfAddonsWaitlistSubscribeDataOneOf1AsNtfAddonsWaitlistSubscribeData(v *NtfAddonsWaitlistSubscribeDataOneOf1) NtfAddonsWaitlistSubscribeData {
	return NtfAddonsWaitlistSubscribeData{
		NtfAddonsWaitlistSubscribeDataOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *NtfAddonsWaitlistSubscribeData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into NtfAddonsWaitlistSubscribeDataOneOf
	err = newStrictDecoder(data).Decode(&dst.NtfAddonsWaitlistSubscribeDataOneOf)
	if err == nil {
		jsonNtfAddonsWaitlistSubscribeDataOneOf, _ := json.Marshal(dst.NtfAddonsWaitlistSubscribeDataOneOf)
		if string(jsonNtfAddonsWaitlistSubscribeDataOneOf) == "{}" { // empty struct
			dst.NtfAddonsWaitlistSubscribeDataOneOf = nil
		} else {
			if err = validator.Validate(dst.NtfAddonsWaitlistSubscribeDataOneOf); err != nil {
				dst.NtfAddonsWaitlistSubscribeDataOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.NtfAddonsWaitlistSubscribeDataOneOf = nil
	}

	// try to unmarshal data into NtfAddonsWaitlistSubscribeDataOneOf1
	err = newStrictDecoder(data).Decode(&dst.NtfAddonsWaitlistSubscribeDataOneOf1)
	if err == nil {
		jsonNtfAddonsWaitlistSubscribeDataOneOf1, _ := json.Marshal(dst.NtfAddonsWaitlistSubscribeDataOneOf1)
		if string(jsonNtfAddonsWaitlistSubscribeDataOneOf1) == "{}" { // empty struct
			dst.NtfAddonsWaitlistSubscribeDataOneOf1 = nil
		} else {
			if err = validator.Validate(dst.NtfAddonsWaitlistSubscribeDataOneOf1); err != nil {
				dst.NtfAddonsWaitlistSubscribeDataOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.NtfAddonsWaitlistSubscribeDataOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.NtfAddonsWaitlistSubscribeDataOneOf = nil
		dst.NtfAddonsWaitlistSubscribeDataOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(NtfAddonsWaitlistSubscribeData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(NtfAddonsWaitlistSubscribeData): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(NtfAddonsWaitlistSubscribeData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NtfAddonsWaitlistSubscribeData) MarshalJSON() ([]byte, error) {
	if src.NtfAddonsWaitlistSubscribeDataOneOf != nil {
		return json.Marshal(&src.NtfAddonsWaitlistSubscribeDataOneOf)
	}

	if src.NtfAddonsWaitlistSubscribeDataOneOf1 != nil {
		return json.Marshal(&src.NtfAddonsWaitlistSubscribeDataOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NtfAddonsWaitlistSubscribeData) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.NtfAddonsWaitlistSubscribeDataOneOf != nil {
		return obj.NtfAddonsWaitlistSubscribeDataOneOf
	}

	if obj.NtfAddonsWaitlistSubscribeDataOneOf1 != nil {
		return obj.NtfAddonsWaitlistSubscribeDataOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj NtfAddonsWaitlistSubscribeData) GetActualInstanceValue() (interface{}) {
	if obj.NtfAddonsWaitlistSubscribeDataOneOf != nil {
		return *obj.NtfAddonsWaitlistSubscribeDataOneOf
	}

	if obj.NtfAddonsWaitlistSubscribeDataOneOf1 != nil {
		return *obj.NtfAddonsWaitlistSubscribeDataOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableNtfAddonsWaitlistSubscribeData struct {
	value *NtfAddonsWaitlistSubscribeData
	isSet bool
}

func (v NullableNtfAddonsWaitlistSubscribeData) Get() *NtfAddonsWaitlistSubscribeData {
	return v.value
}

func (v *NullableNtfAddonsWaitlistSubscribeData) Set(val *NtfAddonsWaitlistSubscribeData) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfAddonsWaitlistSubscribeData) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfAddonsWaitlistSubscribeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfAddonsWaitlistSubscribeData(val *NtfAddonsWaitlistSubscribeData) *NullableNtfAddonsWaitlistSubscribeData {
	return &NullableNtfAddonsWaitlistSubscribeData{value: val, isSet: true}
}

func (v NullableNtfAddonsWaitlistSubscribeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfAddonsWaitlistSubscribeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


