/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfIgReplyCommentResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfIgReplyCommentResponseData{}

// NtfIgReplyCommentResponseData struct for NtfIgReplyCommentResponseData
type NtfIgReplyCommentResponseData struct {
	Id *string `json:"id,omitempty"`
	Text *string `json:"text,omitempty"`
	ParentId *string `json:"parentId,omitempty"`
}

// NewNtfIgReplyCommentResponseData instantiates a new NtfIgReplyCommentResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfIgReplyCommentResponseData() *NtfIgReplyCommentResponseData {
	this := NtfIgReplyCommentResponseData{}
	return &this
}

// NewNtfIgReplyCommentResponseDataWithDefaults instantiates a new NtfIgReplyCommentResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfIgReplyCommentResponseDataWithDefaults() *NtfIgReplyCommentResponseData {
	this := NtfIgReplyCommentResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NtfIgReplyCommentResponseData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfIgReplyCommentResponseData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NtfIgReplyCommentResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NtfIgReplyCommentResponseData) SetId(v string) {
	o.Id = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *NtfIgReplyCommentResponseData) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfIgReplyCommentResponseData) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *NtfIgReplyCommentResponseData) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *NtfIgReplyCommentResponseData) SetText(v string) {
	o.Text = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *NtfIgReplyCommentResponseData) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfIgReplyCommentResponseData) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *NtfIgReplyCommentResponseData) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *NtfIgReplyCommentResponseData) SetParentId(v string) {
	o.ParentId = &v
}

func (o NtfIgReplyCommentResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfIgReplyCommentResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	return toSerialize, nil
}

type NullableNtfIgReplyCommentResponseData struct {
	value *NtfIgReplyCommentResponseData
	isSet bool
}

func (v NullableNtfIgReplyCommentResponseData) Get() *NtfIgReplyCommentResponseData {
	return v.value
}

func (v *NullableNtfIgReplyCommentResponseData) Set(val *NtfIgReplyCommentResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfIgReplyCommentResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfIgReplyCommentResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfIgReplyCommentResponseData(val *NtfIgReplyCommentResponseData) *NullableNtfIgReplyCommentResponseData {
	return &NullableNtfIgReplyCommentResponseData{value: val, isSet: true}
}

func (v NullableNtfIgReplyCommentResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfIgReplyCommentResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


