/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NtfIgResolveChallengeBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfIgResolveChallengeBody{}

// NtfIgResolveChallengeBody struct for NtfIgResolveChallengeBody
type NtfIgResolveChallengeBody struct {
	// Payload do desafio retornado no login (data.challenge / lastJson).
	LastJson map[string]interface{} `json:"lastJson"`
	SecurityCode string `json:"securityCode"`
}

type _NtfIgResolveChallengeBody NtfIgResolveChallengeBody

// NewNtfIgResolveChallengeBody instantiates a new NtfIgResolveChallengeBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfIgResolveChallengeBody(lastJson map[string]interface{}, securityCode string) *NtfIgResolveChallengeBody {
	this := NtfIgResolveChallengeBody{}
	this.LastJson = lastJson
	this.SecurityCode = securityCode
	return &this
}

// NewNtfIgResolveChallengeBodyWithDefaults instantiates a new NtfIgResolveChallengeBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfIgResolveChallengeBodyWithDefaults() *NtfIgResolveChallengeBody {
	this := NtfIgResolveChallengeBody{}
	return &this
}

// GetLastJson returns the LastJson field value
func (o *NtfIgResolveChallengeBody) GetLastJson() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.LastJson
}

// GetLastJsonOk returns a tuple with the LastJson field value
// and a boolean to check if the value has been set.
func (o *NtfIgResolveChallengeBody) GetLastJsonOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.LastJson, true
}

// SetLastJson sets field value
func (o *NtfIgResolveChallengeBody) SetLastJson(v map[string]interface{}) {
	o.LastJson = v
}

// GetSecurityCode returns the SecurityCode field value
func (o *NtfIgResolveChallengeBody) GetSecurityCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecurityCode
}

// GetSecurityCodeOk returns a tuple with the SecurityCode field value
// and a boolean to check if the value has been set.
func (o *NtfIgResolveChallengeBody) GetSecurityCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecurityCode, true
}

// SetSecurityCode sets field value
func (o *NtfIgResolveChallengeBody) SetSecurityCode(v string) {
	o.SecurityCode = v
}

func (o NtfIgResolveChallengeBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfIgResolveChallengeBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lastJson"] = o.LastJson
	toSerialize["securityCode"] = o.SecurityCode
	return toSerialize, nil
}

func (o *NtfIgResolveChallengeBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lastJson",
		"securityCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNtfIgResolveChallengeBody := _NtfIgResolveChallengeBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNtfIgResolveChallengeBody)

	if err != nil {
		return err
	}

	*o = NtfIgResolveChallengeBody(varNtfIgResolveChallengeBody)

	return err
}

type NullableNtfIgResolveChallengeBody struct {
	value *NtfIgResolveChallengeBody
	isSet bool
}

func (v NullableNtfIgResolveChallengeBody) Get() *NtfIgResolveChallengeBody {
	return v.value
}

func (v *NullableNtfIgResolveChallengeBody) Set(val *NtfIgResolveChallengeBody) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfIgResolveChallengeBody) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfIgResolveChallengeBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfIgResolveChallengeBody(val *NtfIgResolveChallengeBody) *NullableNtfIgResolveChallengeBody {
	return &NullableNtfIgResolveChallengeBody{value: val, isSet: true}
}

func (v NullableNtfIgResolveChallengeBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfIgResolveChallengeBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


