/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfEmailDomainVerificationView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfEmailDomainVerificationView{}

// NtfEmailDomainVerificationView struct for NtfEmailDomainVerificationView
type NtfEmailDomainVerificationView struct {
	// Identificador da rota de envio primária configurada para o domínio.
	PrimaryProvider *string `json:"primaryProvider,omitempty"`
	DomainStatus *string `json:"domainStatus,omitempty"`
	Providers []NtfEmailDomainProviderVerification `json:"providers,omitempty"`
	Records *NtfEmailDomainVerificationViewRecords `json:"records,omitempty"`
}

// NewNtfEmailDomainVerificationView instantiates a new NtfEmailDomainVerificationView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfEmailDomainVerificationView() *NtfEmailDomainVerificationView {
	this := NtfEmailDomainVerificationView{}
	return &this
}

// NewNtfEmailDomainVerificationViewWithDefaults instantiates a new NtfEmailDomainVerificationView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfEmailDomainVerificationViewWithDefaults() *NtfEmailDomainVerificationView {
	this := NtfEmailDomainVerificationView{}
	return &this
}

// GetPrimaryProvider returns the PrimaryProvider field value if set, zero value otherwise.
func (o *NtfEmailDomainVerificationView) GetPrimaryProvider() string {
	if o == nil || IsNil(o.PrimaryProvider) {
		var ret string
		return ret
	}
	return *o.PrimaryProvider
}

// GetPrimaryProviderOk returns a tuple with the PrimaryProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfEmailDomainVerificationView) GetPrimaryProviderOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryProvider) {
		return nil, false
	}
	return o.PrimaryProvider, true
}

// HasPrimaryProvider returns a boolean if a field has been set.
func (o *NtfEmailDomainVerificationView) HasPrimaryProvider() bool {
	if o != nil && !IsNil(o.PrimaryProvider) {
		return true
	}

	return false
}

// SetPrimaryProvider gets a reference to the given string and assigns it to the PrimaryProvider field.
func (o *NtfEmailDomainVerificationView) SetPrimaryProvider(v string) {
	o.PrimaryProvider = &v
}

// GetDomainStatus returns the DomainStatus field value if set, zero value otherwise.
func (o *NtfEmailDomainVerificationView) GetDomainStatus() string {
	if o == nil || IsNil(o.DomainStatus) {
		var ret string
		return ret
	}
	return *o.DomainStatus
}

// GetDomainStatusOk returns a tuple with the DomainStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfEmailDomainVerificationView) GetDomainStatusOk() (*string, bool) {
	if o == nil || IsNil(o.DomainStatus) {
		return nil, false
	}
	return o.DomainStatus, true
}

// HasDomainStatus returns a boolean if a field has been set.
func (o *NtfEmailDomainVerificationView) HasDomainStatus() bool {
	if o != nil && !IsNil(o.DomainStatus) {
		return true
	}

	return false
}

// SetDomainStatus gets a reference to the given string and assigns it to the DomainStatus field.
func (o *NtfEmailDomainVerificationView) SetDomainStatus(v string) {
	o.DomainStatus = &v
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *NtfEmailDomainVerificationView) GetProviders() []NtfEmailDomainProviderVerification {
	if o == nil || IsNil(o.Providers) {
		var ret []NtfEmailDomainProviderVerification
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfEmailDomainVerificationView) GetProvidersOk() ([]NtfEmailDomainProviderVerification, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *NtfEmailDomainVerificationView) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []NtfEmailDomainProviderVerification and assigns it to the Providers field.
func (o *NtfEmailDomainVerificationView) SetProviders(v []NtfEmailDomainProviderVerification) {
	o.Providers = v
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *NtfEmailDomainVerificationView) GetRecords() NtfEmailDomainVerificationViewRecords {
	if o == nil || IsNil(o.Records) {
		var ret NtfEmailDomainVerificationViewRecords
		return ret
	}
	return *o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfEmailDomainVerificationView) GetRecordsOk() (*NtfEmailDomainVerificationViewRecords, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *NtfEmailDomainVerificationView) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given NtfEmailDomainVerificationViewRecords and assigns it to the Records field.
func (o *NtfEmailDomainVerificationView) SetRecords(v NtfEmailDomainVerificationViewRecords) {
	o.Records = &v
}

func (o NtfEmailDomainVerificationView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfEmailDomainVerificationView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrimaryProvider) {
		toSerialize["primaryProvider"] = o.PrimaryProvider
	}
	if !IsNil(o.DomainStatus) {
		toSerialize["domainStatus"] = o.DomainStatus
	}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	if !IsNil(o.Records) {
		toSerialize["records"] = o.Records
	}
	return toSerialize, nil
}

type NullableNtfEmailDomainVerificationView struct {
	value *NtfEmailDomainVerificationView
	isSet bool
}

func (v NullableNtfEmailDomainVerificationView) Get() *NtfEmailDomainVerificationView {
	return v.value
}

func (v *NullableNtfEmailDomainVerificationView) Set(val *NtfEmailDomainVerificationView) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfEmailDomainVerificationView) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfEmailDomainVerificationView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfEmailDomainVerificationView(val *NtfEmailDomainVerificationView) *NullableNtfEmailDomainVerificationView {
	return &NullableNtfEmailDomainVerificationView{value: val, isSet: true}
}

func (v NullableNtfEmailDomainVerificationView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfEmailDomainVerificationView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


