/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NtfAutoAutomationListResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfAutoAutomationListResponseData{}

// NtfAutoAutomationListResponseData struct for NtfAutoAutomationListResponseData
type NtfAutoAutomationListResponseData struct {
	Items []NtfAutoAutomationListResponseDataItemsInner `json:"items"`
	Page int32 `json:"page"`
	Limit int32 `json:"limit"`
	Total int32 `json:"total"`
}

type _NtfAutoAutomationListResponseData NtfAutoAutomationListResponseData

// NewNtfAutoAutomationListResponseData instantiates a new NtfAutoAutomationListResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfAutoAutomationListResponseData(items []NtfAutoAutomationListResponseDataItemsInner, page int32, limit int32, total int32) *NtfAutoAutomationListResponseData {
	this := NtfAutoAutomationListResponseData{}
	this.Items = items
	this.Page = page
	this.Limit = limit
	this.Total = total
	return &this
}

// NewNtfAutoAutomationListResponseDataWithDefaults instantiates a new NtfAutoAutomationListResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfAutoAutomationListResponseDataWithDefaults() *NtfAutoAutomationListResponseData {
	this := NtfAutoAutomationListResponseData{}
	return &this
}

// GetItems returns the Items field value
func (o *NtfAutoAutomationListResponseData) GetItems() []NtfAutoAutomationListResponseDataItemsInner {
	if o == nil {
		var ret []NtfAutoAutomationListResponseDataItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *NtfAutoAutomationListResponseData) GetItemsOk() ([]NtfAutoAutomationListResponseDataItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *NtfAutoAutomationListResponseData) SetItems(v []NtfAutoAutomationListResponseDataItemsInner) {
	o.Items = v
}

// GetPage returns the Page field value
func (o *NtfAutoAutomationListResponseData) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *NtfAutoAutomationListResponseData) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *NtfAutoAutomationListResponseData) SetPage(v int32) {
	o.Page = v
}

// GetLimit returns the Limit field value
func (o *NtfAutoAutomationListResponseData) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *NtfAutoAutomationListResponseData) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *NtfAutoAutomationListResponseData) SetLimit(v int32) {
	o.Limit = v
}

// GetTotal returns the Total field value
func (o *NtfAutoAutomationListResponseData) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *NtfAutoAutomationListResponseData) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *NtfAutoAutomationListResponseData) SetTotal(v int32) {
	o.Total = v
}

func (o NtfAutoAutomationListResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfAutoAutomationListResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["page"] = o.Page
	toSerialize["limit"] = o.Limit
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *NtfAutoAutomationListResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"page",
		"limit",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNtfAutoAutomationListResponseData := _NtfAutoAutomationListResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNtfAutoAutomationListResponseData)

	if err != nil {
		return err
	}

	*o = NtfAutoAutomationListResponseData(varNtfAutoAutomationListResponseData)

	return err
}

type NullableNtfAutoAutomationListResponseData struct {
	value *NtfAutoAutomationListResponseData
	isSet bool
}

func (v NullableNtfAutoAutomationListResponseData) Get() *NtfAutoAutomationListResponseData {
	return v.value
}

func (v *NullableNtfAutoAutomationListResponseData) Set(val *NtfAutoAutomationListResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfAutoAutomationListResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfAutoAutomationListResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfAutoAutomationListResponseData(val *NtfAutoAutomationListResponseData) *NullableNtfAutoAutomationListResponseData {
	return &NullableNtfAutoAutomationListResponseData{value: val, isSet: true}
}

func (v NullableNtfAutoAutomationListResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfAutoAutomationListResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


