/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfPushDeleteV1PushAppsByIdResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfPushDeleteV1PushAppsByIdResponse{}

// NtfPushDeleteV1PushAppsByIdResponse struct for NtfPushDeleteV1PushAppsByIdResponse
type NtfPushDeleteV1PushAppsByIdResponse struct {
	Success *bool `json:"success,omitempty"`
}

// NewNtfPushDeleteV1PushAppsByIdResponse instantiates a new NtfPushDeleteV1PushAppsByIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfPushDeleteV1PushAppsByIdResponse() *NtfPushDeleteV1PushAppsByIdResponse {
	this := NtfPushDeleteV1PushAppsByIdResponse{}
	return &this
}

// NewNtfPushDeleteV1PushAppsByIdResponseWithDefaults instantiates a new NtfPushDeleteV1PushAppsByIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfPushDeleteV1PushAppsByIdResponseWithDefaults() *NtfPushDeleteV1PushAppsByIdResponse {
	this := NtfPushDeleteV1PushAppsByIdResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *NtfPushDeleteV1PushAppsByIdResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfPushDeleteV1PushAppsByIdResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *NtfPushDeleteV1PushAppsByIdResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *NtfPushDeleteV1PushAppsByIdResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o NtfPushDeleteV1PushAppsByIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfPushDeleteV1PushAppsByIdResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableNtfPushDeleteV1PushAppsByIdResponse struct {
	value *NtfPushDeleteV1PushAppsByIdResponse
	isSet bool
}

func (v NullableNtfPushDeleteV1PushAppsByIdResponse) Get() *NtfPushDeleteV1PushAppsByIdResponse {
	return v.value
}

func (v *NullableNtfPushDeleteV1PushAppsByIdResponse) Set(val *NtfPushDeleteV1PushAppsByIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfPushDeleteV1PushAppsByIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfPushDeleteV1PushAppsByIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfPushDeleteV1PushAppsByIdResponse(val *NtfPushDeleteV1PushAppsByIdResponse) *NullableNtfPushDeleteV1PushAppsByIdResponse {
	return &NullableNtfPushDeleteV1PushAppsByIdResponse{value: val, isSet: true}
}

func (v NullableNtfPushDeleteV1PushAppsByIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfPushDeleteV1PushAppsByIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


