/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfContactDeleteV1SegmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfContactDeleteV1SegmentResponse{}

// NtfContactDeleteV1SegmentResponse struct for NtfContactDeleteV1SegmentResponse
type NtfContactDeleteV1SegmentResponse struct {
	Success *bool `json:"success,omitempty"`
}

// NewNtfContactDeleteV1SegmentResponse instantiates a new NtfContactDeleteV1SegmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfContactDeleteV1SegmentResponse() *NtfContactDeleteV1SegmentResponse {
	this := NtfContactDeleteV1SegmentResponse{}
	return &this
}

// NewNtfContactDeleteV1SegmentResponseWithDefaults instantiates a new NtfContactDeleteV1SegmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfContactDeleteV1SegmentResponseWithDefaults() *NtfContactDeleteV1SegmentResponse {
	this := NtfContactDeleteV1SegmentResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *NtfContactDeleteV1SegmentResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfContactDeleteV1SegmentResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *NtfContactDeleteV1SegmentResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *NtfContactDeleteV1SegmentResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o NtfContactDeleteV1SegmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfContactDeleteV1SegmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableNtfContactDeleteV1SegmentResponse struct {
	value *NtfContactDeleteV1SegmentResponse
	isSet bool
}

func (v NullableNtfContactDeleteV1SegmentResponse) Get() *NtfContactDeleteV1SegmentResponse {
	return v.value
}

func (v *NullableNtfContactDeleteV1SegmentResponse) Set(val *NtfContactDeleteV1SegmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfContactDeleteV1SegmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfContactDeleteV1SegmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfContactDeleteV1SegmentResponse(val *NtfContactDeleteV1SegmentResponse) *NullableNtfContactDeleteV1SegmentResponse {
	return &NullableNtfContactDeleteV1SegmentResponse{value: val, isSet: true}
}

func (v NullableNtfContactDeleteV1SegmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfContactDeleteV1SegmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


