/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfEmailDomainVerificationViewRecords type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfEmailDomainVerificationViewRecords{}

// NtfEmailDomainVerificationViewRecords Mapa `TIPO|host` → status (ex.: `TXT|api._domainkey.example.com`).
type NtfEmailDomainVerificationViewRecords struct {
	TXTApiDomainkeySeudominioCom *string `json:"TXT|api._domainkey.seudominio.com,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NtfEmailDomainVerificationViewRecords NtfEmailDomainVerificationViewRecords

// NewNtfEmailDomainVerificationViewRecords instantiates a new NtfEmailDomainVerificationViewRecords object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfEmailDomainVerificationViewRecords() *NtfEmailDomainVerificationViewRecords {
	this := NtfEmailDomainVerificationViewRecords{}
	return &this
}

// NewNtfEmailDomainVerificationViewRecordsWithDefaults instantiates a new NtfEmailDomainVerificationViewRecords object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfEmailDomainVerificationViewRecordsWithDefaults() *NtfEmailDomainVerificationViewRecords {
	this := NtfEmailDomainVerificationViewRecords{}
	return &this
}

// GetTXTApiDomainkeySeudominioCom returns the TXTApiDomainkeySeudominioCom field value if set, zero value otherwise.
func (o *NtfEmailDomainVerificationViewRecords) GetTXTApiDomainkeySeudominioCom() string {
	if o == nil || IsNil(o.TXTApiDomainkeySeudominioCom) {
		var ret string
		return ret
	}
	return *o.TXTApiDomainkeySeudominioCom
}

// GetTXTApiDomainkeySeudominioComOk returns a tuple with the TXTApiDomainkeySeudominioCom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfEmailDomainVerificationViewRecords) GetTXTApiDomainkeySeudominioComOk() (*string, bool) {
	if o == nil || IsNil(o.TXTApiDomainkeySeudominioCom) {
		return nil, false
	}
	return o.TXTApiDomainkeySeudominioCom, true
}

// HasTXTApiDomainkeySeudominioCom returns a boolean if a field has been set.
func (o *NtfEmailDomainVerificationViewRecords) HasTXTApiDomainkeySeudominioCom() bool {
	if o != nil && !IsNil(o.TXTApiDomainkeySeudominioCom) {
		return true
	}

	return false
}

// SetTXTApiDomainkeySeudominioCom gets a reference to the given string and assigns it to the TXTApiDomainkeySeudominioCom field.
func (o *NtfEmailDomainVerificationViewRecords) SetTXTApiDomainkeySeudominioCom(v string) {
	o.TXTApiDomainkeySeudominioCom = &v
}

func (o NtfEmailDomainVerificationViewRecords) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfEmailDomainVerificationViewRecords) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TXTApiDomainkeySeudominioCom) {
		toSerialize["TXT|api._domainkey.seudominio.com"] = o.TXTApiDomainkeySeudominioCom
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NtfEmailDomainVerificationViewRecords) UnmarshalJSON(data []byte) (err error) {
	varNtfEmailDomainVerificationViewRecords := _NtfEmailDomainVerificationViewRecords{}

	err = json.Unmarshal(data, &varNtfEmailDomainVerificationViewRecords)

	if err != nil {
		return err
	}

	*o = NtfEmailDomainVerificationViewRecords(varNtfEmailDomainVerificationViewRecords)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "TXT|api._domainkey.seudominio.com")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNtfEmailDomainVerificationViewRecords struct {
	value *NtfEmailDomainVerificationViewRecords
	isSet bool
}

func (v NullableNtfEmailDomainVerificationViewRecords) Get() *NtfEmailDomainVerificationViewRecords {
	return v.value
}

func (v *NullableNtfEmailDomainVerificationViewRecords) Set(val *NtfEmailDomainVerificationViewRecords) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfEmailDomainVerificationViewRecords) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfEmailDomainVerificationViewRecords) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfEmailDomainVerificationViewRecords(val *NtfEmailDomainVerificationViewRecords) *NullableNtfEmailDomainVerificationViewRecords {
	return &NullableNtfEmailDomainVerificationViewRecords{value: val, isSet: true}
}

func (v NullableNtfEmailDomainVerificationViewRecords) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfEmailDomainVerificationViewRecords) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


