/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfWaWhatsAppCallDetailEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfWaWhatsAppCallDetailEnvelope{}

// NtfWaWhatsAppCallDetailEnvelope struct for NtfWaWhatsAppCallDetailEnvelope
type NtfWaWhatsAppCallDetailEnvelope struct {
	Success *bool `json:"success,omitempty"`
	Data *NtfWaWhatsAppCallDetailEnvelopeData `json:"data,omitempty"`
}

// NewNtfWaWhatsAppCallDetailEnvelope instantiates a new NtfWaWhatsAppCallDetailEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfWaWhatsAppCallDetailEnvelope() *NtfWaWhatsAppCallDetailEnvelope {
	this := NtfWaWhatsAppCallDetailEnvelope{}
	return &this
}

// NewNtfWaWhatsAppCallDetailEnvelopeWithDefaults instantiates a new NtfWaWhatsAppCallDetailEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfWaWhatsAppCallDetailEnvelopeWithDefaults() *NtfWaWhatsAppCallDetailEnvelope {
	this := NtfWaWhatsAppCallDetailEnvelope{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *NtfWaWhatsAppCallDetailEnvelope) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWaWhatsAppCallDetailEnvelope) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *NtfWaWhatsAppCallDetailEnvelope) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *NtfWaWhatsAppCallDetailEnvelope) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NtfWaWhatsAppCallDetailEnvelope) GetData() NtfWaWhatsAppCallDetailEnvelopeData {
	if o == nil || IsNil(o.Data) {
		var ret NtfWaWhatsAppCallDetailEnvelopeData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfWaWhatsAppCallDetailEnvelope) GetDataOk() (*NtfWaWhatsAppCallDetailEnvelopeData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NtfWaWhatsAppCallDetailEnvelope) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given NtfWaWhatsAppCallDetailEnvelopeData and assigns it to the Data field.
func (o *NtfWaWhatsAppCallDetailEnvelope) SetData(v NtfWaWhatsAppCallDetailEnvelopeData) {
	o.Data = &v
}

func (o NtfWaWhatsAppCallDetailEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfWaWhatsAppCallDetailEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableNtfWaWhatsAppCallDetailEnvelope struct {
	value *NtfWaWhatsAppCallDetailEnvelope
	isSet bool
}

func (v NullableNtfWaWhatsAppCallDetailEnvelope) Get() *NtfWaWhatsAppCallDetailEnvelope {
	return v.value
}

func (v *NullableNtfWaWhatsAppCallDetailEnvelope) Set(val *NtfWaWhatsAppCallDetailEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfWaWhatsAppCallDetailEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfWaWhatsAppCallDetailEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfWaWhatsAppCallDetailEnvelope(val *NtfWaWhatsAppCallDetailEnvelope) *NullableNtfWaWhatsAppCallDetailEnvelope {
	return &NullableNtfWaWhatsAppCallDetailEnvelope{value: val, isSet: true}
}

func (v NullableNtfWaWhatsAppCallDetailEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfWaWhatsAppCallDetailEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


