/*
Notifique API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapimodels

import (
	"encoding/json"
)

// checks if the NtfAutoHttpListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NtfAutoHttpListResponse{}

// NtfAutoHttpListResponse struct for NtfAutoHttpListResponse
type NtfAutoHttpListResponse struct {
	Success *bool `json:"success,omitempty"`
	Data []map[string]interface{} `json:"data,omitempty"`
}

// NewNtfAutoHttpListResponse instantiates a new NtfAutoHttpListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNtfAutoHttpListResponse() *NtfAutoHttpListResponse {
	this := NtfAutoHttpListResponse{}
	return &this
}

// NewNtfAutoHttpListResponseWithDefaults instantiates a new NtfAutoHttpListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNtfAutoHttpListResponseWithDefaults() *NtfAutoHttpListResponse {
	this := NtfAutoHttpListResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *NtfAutoHttpListResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfAutoHttpListResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *NtfAutoHttpListResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *NtfAutoHttpListResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NtfAutoHttpListResponse) GetData() []map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NtfAutoHttpListResponse) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NtfAutoHttpListResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []map[string]interface{} and assigns it to the Data field.
func (o *NtfAutoHttpListResponse) SetData(v []map[string]interface{}) {
	o.Data = v
}

func (o NtfAutoHttpListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NtfAutoHttpListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableNtfAutoHttpListResponse struct {
	value *NtfAutoHttpListResponse
	isSet bool
}

func (v NullableNtfAutoHttpListResponse) Get() *NtfAutoHttpListResponse {
	return v.value
}

func (v *NullableNtfAutoHttpListResponse) Set(val *NtfAutoHttpListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNtfAutoHttpListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNtfAutoHttpListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNtfAutoHttpListResponse(val *NtfAutoHttpListResponse) *NullableNtfAutoHttpListResponse {
	return &NullableNtfAutoHttpListResponse{value: val, isSet: true}
}

func (v NullableNtfAutoHttpListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNtfAutoHttpListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


